// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v6.33.1
// source: api/core/v1/statistic/statistic.proto

package statistic

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationStatisticHeatmap = "/api.core.v1.statistic.Statistic/Heatmap"

type StatisticHTTPServer interface {
	Heatmap(context.Context, *HeatmapReq) (*HeatmapResp, error)
}

func RegisterStatisticHTTPServer(s *http.Server, srv StatisticHTTPServer) {
	r := s.Route("/")
	r.GET("/api/core/v1/statistic/heatmap", _Statistic_Heatmap0_HTTP_Handler(srv))
}

func _Statistic_Heatmap0_HTTP_Handler(srv StatisticHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in HeatmapReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationStatisticHeatmap)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Heatmap(ctx, req.(*HeatmapReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*HeatmapResp)
		return ctx.Result(200, reply)
	}
}

type StatisticHTTPClient interface {
	Heatmap(ctx context.Context, req *HeatmapReq, opts ...http.CallOption) (rsp *HeatmapResp, err error)
}

type StatisticHTTPClientImpl struct {
	cc *http.Client
}

func NewStatisticHTTPClient(client *http.Client) StatisticHTTPClient {
	return &StatisticHTTPClientImpl{client}
}

func (c *StatisticHTTPClientImpl) Heatmap(ctx context.Context, in *HeatmapReq, opts ...http.CallOption) (*HeatmapResp, error) {
	var out HeatmapResp
	pattern := "/api/core/v1/statistic/heatmap"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationStatisticHeatmap))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
