// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: api/core/v1/statistic/statistic.proto

package statistic

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HeatmapReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	StartDate     string                 `protobuf:"bytes,2,opt,name=startDate,proto3" json:"startDate,omitempty"`
	EndDate       string                 `protobuf:"bytes,3,opt,name=endDate,proto3" json:"endDate,omitempty"`
	IsAc          bool                   `protobuf:"varint,4,opt,name=isAc,proto3" json:"isAc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeatmapReq) Reset() {
	*x = HeatmapReq{}
	mi := &file_api_core_v1_statistic_statistic_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeatmapReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeatmapReq) ProtoMessage() {}

func (x *HeatmapReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_core_v1_statistic_statistic_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeatmapReq.ProtoReflect.Descriptor instead.
func (*HeatmapReq) Descriptor() ([]byte, []int) {
	return file_api_core_v1_statistic_statistic_proto_rawDescGZIP(), []int{0}
}

func (x *HeatmapReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *HeatmapReq) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *HeatmapReq) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *HeatmapReq) GetIsAc() bool {
	if x != nil {
		return x.IsAc
	}
	return false
}

type HeatmapResp struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Code          int64                      `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Data          []*HeatmapResp_HeatmapItem `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeatmapResp) Reset() {
	*x = HeatmapResp{}
	mi := &file_api_core_v1_statistic_statistic_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeatmapResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeatmapResp) ProtoMessage() {}

func (x *HeatmapResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_core_v1_statistic_statistic_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeatmapResp.ProtoReflect.Descriptor instead.
func (*HeatmapResp) Descriptor() ([]byte, []int) {
	return file_api_core_v1_statistic_statistic_proto_rawDescGZIP(), []int{1}
}

func (x *HeatmapResp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *HeatmapResp) GetData() []*HeatmapResp_HeatmapItem {
	if x != nil {
		return x.Data
	}
	return nil
}

type HeatmapResp_HeatmapItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeatmapResp_HeatmapItem) Reset() {
	*x = HeatmapResp_HeatmapItem{}
	mi := &file_api_core_v1_statistic_statistic_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeatmapResp_HeatmapItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeatmapResp_HeatmapItem) ProtoMessage() {}

func (x *HeatmapResp_HeatmapItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_core_v1_statistic_statistic_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeatmapResp_HeatmapItem.ProtoReflect.Descriptor instead.
func (*HeatmapResp_HeatmapItem) Descriptor() ([]byte, []int) {
	return file_api_core_v1_statistic_statistic_proto_rawDescGZIP(), []int{1, 0}
}

func (x *HeatmapResp_HeatmapItem) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *HeatmapResp_HeatmapItem) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_api_core_v1_statistic_statistic_proto protoreflect.FileDescriptor

const file_api_core_v1_statistic_statistic_proto_rawDesc = "" +
	"\n" +
	"%api/core/v1/statistic/statistic.proto\x12\x15api.core.v1.statistic\x1a\x1cgoogle/api/annotations.proto\"p\n" +
	"\n" +
	"HeatmapReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x1c\n" +
	"\tstartDate\x18\x02 \x01(\tR\tstartDate\x12\x18\n" +
	"\aendDate\x18\x03 \x01(\tR\aendDate\x12\x12\n" +
	"\x04isAc\x18\x04 \x01(\bR\x04isAc\"\x9e\x01\n" +
	"\vHeatmapResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12B\n" +
	"\x04data\x18\x02 \x03(\v2..api.core.v1.statistic.HeatmapResp.HeatmapItemR\x04data\x1a7\n" +
	"\vHeatmapItem\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count2\x81\x01\n" +
	"\tStatistic\x12t\n" +
	"\aHeatmap\x12!.api.core.v1.statistic.HeatmapReq\x1a\".api.core.v1.statistic.HeatmapResp\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/v1/core/statistic/heatmapBD\n" +
	"\x15api.core.v1.statisticP\x01Z)cwxu-algo/api/core/v1/statistic;statisticb\x06proto3"

var (
	file_api_core_v1_statistic_statistic_proto_rawDescOnce sync.Once
	file_api_core_v1_statistic_statistic_proto_rawDescData []byte
)

func file_api_core_v1_statistic_statistic_proto_rawDescGZIP() []byte {
	file_api_core_v1_statistic_statistic_proto_rawDescOnce.Do(func() {
		file_api_core_v1_statistic_statistic_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_core_v1_statistic_statistic_proto_rawDesc), len(file_api_core_v1_statistic_statistic_proto_rawDesc)))
	})
	return file_api_core_v1_statistic_statistic_proto_rawDescData
}

var file_api_core_v1_statistic_statistic_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_core_v1_statistic_statistic_proto_goTypes = []any{
	(*HeatmapReq)(nil),              // 0: api.core.v1.statistic.HeatmapReq
	(*HeatmapResp)(nil),             // 1: api.core.v1.statistic.HeatmapResp
	(*HeatmapResp_HeatmapItem)(nil), // 2: api.core.v1.statistic.HeatmapResp.HeatmapItem
}
var file_api_core_v1_statistic_statistic_proto_depIdxs = []int32{
	2, // 0: api.core.v1.statistic.HeatmapResp.data:type_name -> api.core.v1.statistic.HeatmapResp.HeatmapItem
	0, // 1: api.core.v1.statistic.Statistic.Heatmap:input_type -> api.core.v1.statistic.HeatmapReq
	1, // 2: api.core.v1.statistic.Statistic.Heatmap:output_type -> api.core.v1.statistic.HeatmapResp
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_core_v1_statistic_statistic_proto_init() }
func file_api_core_v1_statistic_statistic_proto_init() {
	if File_api_core_v1_statistic_statistic_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_core_v1_statistic_statistic_proto_rawDesc), len(file_api_core_v1_statistic_statistic_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_core_v1_statistic_statistic_proto_goTypes,
		DependencyIndexes: file_api_core_v1_statistic_statistic_proto_depIdxs,
		MessageInfos:      file_api_core_v1_statistic_statistic_proto_msgTypes,
	}.Build()
	File_api_core_v1_statistic_statistic_proto = out.File
	file_api_core_v1_statistic_statistic_proto_goTypes = nil
	file_api_core_v1_statistic_statistic_proto_depIdxs = nil
}
