// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: core/v1/problem/problem.proto

package problem

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SolutionMeta struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Name             string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	TimeComplexity   string                 `protobuf:"bytes,2,opt,name=time_complexity,json=timeComplexity,proto3" json:"time_complexity,omitempty"`
	SpaceComplexity  string                 `protobuf:"bytes,3,opt,name=space_complexity,json=spaceComplexity,proto3" json:"space_complexity,omitempty"`
	BriefExplanation string                 `protobuf:"bytes,4,opt,name=brief_explanation,json=briefExplanation,proto3" json:"brief_explanation,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SolutionMeta) Reset() {
	*x = SolutionMeta{}
	mi := &file_core_v1_problem_problem_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SolutionMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SolutionMeta) ProtoMessage() {}

func (x *SolutionMeta) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_problem_problem_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SolutionMeta.ProtoReflect.Descriptor instead.
func (*SolutionMeta) Descriptor() ([]byte, []int) {
	return file_core_v1_problem_problem_proto_rawDescGZIP(), []int{0}
}

func (x *SolutionMeta) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SolutionMeta) GetTimeComplexity() string {
	if x != nil {
		return x.TimeComplexity
	}
	return ""
}

func (x *SolutionMeta) GetSpaceComplexity() string {
	if x != nil {
		return x.SpaceComplexity
	}
	return ""
}

func (x *SolutionMeta) GetBriefExplanation() string {
	if x != nil {
		return x.BriefExplanation
	}
	return ""
}

type ProblemInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Platform        string                 `protobuf:"bytes,2,opt,name=platform,proto3" json:"platform,omitempty"`
	ExternalId      string                 `protobuf:"bytes,3,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	Title           string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Url             string                 `protobuf:"bytes,5,opt,name=url,proto3" json:"url,omitempty"`
	ContentMd       string                 `protobuf:"bytes,6,opt,name=content_md,json=contentMd,proto3" json:"content_md,omitempty"`
	ProblemType     string                 `protobuf:"bytes,7,opt,name=problem_type,json=problemType,proto3" json:"problem_type,omitempty"`
	Tags            []string               `protobuf:"bytes,8,rep,name=tags,proto3" json:"tags,omitempty"`
	Solutions       []*SolutionMeta        `protobuf:"bytes,9,rep,name=solutions,proto3" json:"solutions,omitempty"`
	Difficulty      string                 `protobuf:"bytes,10,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	Status          string                 `protobuf:"bytes,11,opt,name=status,proto3" json:"status,omitempty"`
	ErrorMsg        string                 `protobuf:"bytes,12,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	LastSubmittedAt int64                  `protobuf:"varint,13,opt,name=last_submitted_at,json=lastSubmittedAt,proto3" json:"last_submitted_at,omitempty"`
	// 当前用户对该题状态: AC / TRIED / NONE（仅 list 且传 userId 时）
	UserStatus    string `protobuf:"bytes,14,opt,name=user_status,json=userStatus,proto3" json:"user_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProblemInfo) Reset() {
	*x = ProblemInfo{}
	mi := &file_core_v1_problem_problem_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProblemInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProblemInfo) ProtoMessage() {}

func (x *ProblemInfo) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_problem_problem_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProblemInfo.ProtoReflect.Descriptor instead.
func (*ProblemInfo) Descriptor() ([]byte, []int) {
	return file_core_v1_problem_problem_proto_rawDescGZIP(), []int{1}
}

func (x *ProblemInfo) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProblemInfo) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *ProblemInfo) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *ProblemInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ProblemInfo) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ProblemInfo) GetContentMd() string {
	if x != nil {
		return x.ContentMd
	}
	return ""
}

func (x *ProblemInfo) GetProblemType() string {
	if x != nil {
		return x.ProblemType
	}
	return ""
}

func (x *ProblemInfo) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ProblemInfo) GetSolutions() []*SolutionMeta {
	if x != nil {
		return x.Solutions
	}
	return nil
}

func (x *ProblemInfo) GetDifficulty() string {
	if x != nil {
		return x.Difficulty
	}
	return ""
}

func (x *ProblemInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ProblemInfo) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *ProblemInfo) GetLastSubmittedAt() int64 {
	if x != nil {
		return x.LastSubmittedAt
	}
	return 0
}

func (x *ProblemInfo) GetUserStatus() string {
	if x != nil {
		return x.UserStatus
	}
	return ""
}

type ListProblemReq struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Page     int64                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize int64                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// 排序: latest_desc(默认) / latest_asc
	Sort string `protobuf:"bytes,3,opt,name=sort,proto3" json:"sort,omitempty"`
	// 多平台逗号分隔
	Platforms string `protobuf:"bytes,4,opt,name=platforms,proto3" json:"platforms,omitempty"`
	// 标签逗号分隔，匹配任一
	Tags string `protobuf:"bytes,5,opt,name=tags,proto3" json:"tags,omitempty"`
	// 用户做题状态过滤: AC / TRIED / NONE（需 user_id）
	UserStatus string `protobuf:"bytes,6,opt,name=user_status,json=userStatus,proto3" json:"user_status,omitempty"`
	UserId     int64  `protobuf:"varint,7,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// 关键词：匹配 title / external_id（模糊）
	Keyword string `protobuf:"bytes,8,opt,name=keyword,proto3" json:"keyword,omitempty"`
	// 难度：简单 / 中等 / 困难
	Difficulty    string `protobuf:"bytes,9,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProblemReq) Reset() {
	*x = ListProblemReq{}
	mi := &file_core_v1_problem_problem_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProblemReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProblemReq) ProtoMessage() {}

func (x *ListProblemReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_problem_problem_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProblemReq.ProtoReflect.Descriptor instead.
func (*ListProblemReq) Descriptor() ([]byte, []int) {
	return file_core_v1_problem_problem_proto_rawDescGZIP(), []int{2}
}

func (x *ListProblemReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListProblemReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListProblemReq) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

func (x *ListProblemReq) GetPlatforms() string {
	if x != nil {
		return x.Platforms
	}
	return ""
}

func (x *ListProblemReq) GetTags() string {
	if x != nil {
		return x.Tags
	}
	return ""
}

func (x *ListProblemReq) GetUserStatus() string {
	if x != nil {
		return x.UserStatus
	}
	return ""
}

func (x *ListProblemReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListProblemReq) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *ListProblemReq) GetDifficulty() string {
	if x != nil {
		return x.Difficulty
	}
	return ""
}

type ListProblemRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*ProblemInfo         `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	Total         int64                  `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	Page          int64                  `protobuf:"varint,5,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int64                  `protobuf:"varint,6,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProblemRes) Reset() {
	*x = ListProblemRes{}
	mi := &file_core_v1_problem_problem_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProblemRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProblemRes) ProtoMessage() {}

func (x *ListProblemRes) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_problem_problem_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProblemRes.ProtoReflect.Descriptor instead.
func (*ListProblemRes) Descriptor() ([]byte, []int) {
	return file_core_v1_problem_problem_proto_rawDescGZIP(), []int{3}
}

func (x *ListProblemRes) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ListProblemRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ListProblemRes) GetData() []*ProblemInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ListProblemRes) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListProblemRes) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListProblemRes) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetProblemReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProblemReq) Reset() {
	*x = GetProblemReq{}
	mi := &file_core_v1_problem_problem_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProblemReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProblemReq) ProtoMessage() {}

func (x *GetProblemReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_problem_problem_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProblemReq.ProtoReflect.Descriptor instead.
func (*GetProblemReq) Descriptor() ([]byte, []int) {
	return file_core_v1_problem_problem_proto_rawDescGZIP(), []int{4}
}

func (x *GetProblemReq) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetProblemRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *ProblemInfo           `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProblemRes) Reset() {
	*x = GetProblemRes{}
	mi := &file_core_v1_problem_problem_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProblemRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProblemRes) ProtoMessage() {}

func (x *GetProblemRes) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_problem_problem_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProblemRes.ProtoReflect.Descriptor instead.
func (*GetProblemRes) Descriptor() ([]byte, []int) {
	return file_core_v1_problem_problem_proto_rawDescGZIP(), []int{5}
}

func (x *GetProblemRes) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetProblemRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetProblemRes) GetData() *ProblemInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

type SubmissionInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Platform      string                 `protobuf:"bytes,3,opt,name=platform,proto3" json:"platform,omitempty"`
	SubmitId      string                 `protobuf:"bytes,4,opt,name=submit_id,json=submitId,proto3" json:"submit_id,omitempty"`
	Lang          string                 `protobuf:"bytes,5,opt,name=lang,proto3" json:"lang,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Time          int64                  `protobuf:"varint,7,opt,name=time,proto3" json:"time,omitempty"`
	Contest       string                 `protobuf:"bytes,8,opt,name=contest,proto3" json:"contest,omitempty"`
	UserName      string                 `protobuf:"bytes,9,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"` // 展示用姓名
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmissionInfo) Reset() {
	*x = SubmissionInfo{}
	mi := &file_core_v1_problem_problem_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmissionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmissionInfo) ProtoMessage() {}

func (x *SubmissionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_problem_problem_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmissionInfo.ProtoReflect.Descriptor instead.
func (*SubmissionInfo) Descriptor() ([]byte, []int) {
	return file_core_v1_problem_problem_proto_rawDescGZIP(), []int{6}
}

func (x *SubmissionInfo) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SubmissionInfo) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SubmissionInfo) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *SubmissionInfo) GetSubmitId() string {
	if x != nil {
		return x.SubmitId
	}
	return ""
}

func (x *SubmissionInfo) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

func (x *SubmissionInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SubmissionInfo) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *SubmissionInfo) GetContest() string {
	if x != nil {
		return x.Contest
	}
	return ""
}

func (x *SubmissionInfo) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

type ListSubmissionsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProblemId     uint32                 `protobuf:"varint,1,opt,name=problem_id,json=problemId,proto3" json:"problem_id,omitempty"`
	Page          int64                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int64                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	UserId        int64                  `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSubmissionsReq) Reset() {
	*x = ListSubmissionsReq{}
	mi := &file_core_v1_problem_problem_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSubmissionsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSubmissionsReq) ProtoMessage() {}

func (x *ListSubmissionsReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_problem_problem_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSubmissionsReq.ProtoReflect.Descriptor instead.
func (*ListSubmissionsReq) Descriptor() ([]byte, []int) {
	return file_core_v1_problem_problem_proto_rawDescGZIP(), []int{7}
}

func (x *ListSubmissionsReq) GetProblemId() uint32 {
	if x != nil {
		return x.ProblemId
	}
	return 0
}

func (x *ListSubmissionsReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListSubmissionsReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListSubmissionsReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ListSubmissionsRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*SubmissionInfo      `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	Total         int64                  `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSubmissionsRes) Reset() {
	*x = ListSubmissionsRes{}
	mi := &file_core_v1_problem_problem_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSubmissionsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSubmissionsRes) ProtoMessage() {}

func (x *ListSubmissionsRes) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_problem_problem_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSubmissionsRes.ProtoReflect.Descriptor instead.
func (*ListSubmissionsRes) Descriptor() ([]byte, []int) {
	return file_core_v1_problem_problem_proto_rawDescGZIP(), []int{8}
}

func (x *ListSubmissionsRes) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ListSubmissionsRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ListSubmissionsRes) GetData() []*SubmissionInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ListSubmissionsRes) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type TagScore struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tag           string                 `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	Score         float64                `protobuf:"fixed64,2,opt,name=score,proto3" json:"score,omitempty"`
	AcCount       int64                  `protobuf:"varint,3,opt,name=ac_count,json=acCount,proto3" json:"ac_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagScore) Reset() {
	*x = TagScore{}
	mi := &file_core_v1_problem_problem_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagScore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagScore) ProtoMessage() {}

func (x *TagScore) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_problem_problem_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagScore.ProtoReflect.Descriptor instead.
func (*TagScore) Descriptor() ([]byte, []int) {
	return file_core_v1_problem_problem_proto_rawDescGZIP(), []int{9}
}

func (x *TagScore) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *TagScore) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *TagScore) GetAcCount() int64 {
	if x != nil {
		return x.AcCount
	}
	return 0
}

type NamedCount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NamedCount) Reset() {
	*x = NamedCount{}
	mi := &file_core_v1_problem_problem_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NamedCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NamedCount) ProtoMessage() {}

func (x *NamedCount) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_problem_problem_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NamedCount.ProtoReflect.Descriptor instead.
func (*NamedCount) Descriptor() ([]byte, []int) {
	return file_core_v1_problem_problem_proto_rawDescGZIP(), []int{10}
}

func (x *NamedCount) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NamedCount) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type UserProfileReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserProfileReq) Reset() {
	*x = UserProfileReq{}
	mi := &file_core_v1_problem_problem_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProfileReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProfileReq) ProtoMessage() {}

func (x *UserProfileReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_problem_problem_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProfileReq.ProtoReflect.Descriptor instead.
func (*UserProfileReq) Descriptor() ([]byte, []int) {
	return file_core_v1_problem_problem_proto_rawDescGZIP(), []int{11}
}

func (x *UserProfileReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type UserProfileRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Radar         []*TagScore            `protobuf:"bytes,3,rep,name=radar,proto3" json:"radar,omitempty"`
	Platforms     []*NamedCount          `protobuf:"bytes,4,rep,name=platforms,proto3" json:"platforms,omitempty"`
	Difficulties  []*NamedCount          `protobuf:"bytes,5,rep,name=difficulties,proto3" json:"difficulties,omitempty"`
	TotalAc       int64                  `protobuf:"varint,6,opt,name=total_ac,json=totalAc,proto3" json:"total_ac,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserProfileRes) Reset() {
	*x = UserProfileRes{}
	mi := &file_core_v1_problem_problem_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProfileRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProfileRes) ProtoMessage() {}

func (x *UserProfileRes) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_problem_problem_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProfileRes.ProtoReflect.Descriptor instead.
func (*UserProfileRes) Descriptor() ([]byte, []int) {
	return file_core_v1_problem_problem_proto_rawDescGZIP(), []int{12}
}

func (x *UserProfileRes) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UserProfileRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UserProfileRes) GetRadar() []*TagScore {
	if x != nil {
		return x.Radar
	}
	return nil
}

func (x *UserProfileRes) GetPlatforms() []*NamedCount {
	if x != nil {
		return x.Platforms
	}
	return nil
}

func (x *UserProfileRes) GetDifficulties() []*NamedCount {
	if x != nil {
		return x.Difficulties
	}
	return nil
}

func (x *UserProfileRes) GetTotalAc() int64 {
	if x != nil {
		return x.TotalAc
	}
	return 0
}

type ProgressReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProgressReq) Reset() {
	*x = ProgressReq{}
	mi := &file_core_v1_problem_problem_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgressReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgressReq) ProtoMessage() {}

func (x *ProgressReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_problem_problem_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgressReq.ProtoReflect.Descriptor instead.
func (*ProgressReq) Descriptor() ([]byte, []int) {
	return file_core_v1_problem_problem_proto_rawDescGZIP(), []int{13}
}

type ProgressItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProgressItem) Reset() {
	*x = ProgressItem{}
	mi := &file_core_v1_problem_problem_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgressItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgressItem) ProtoMessage() {}

func (x *ProgressItem) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_problem_problem_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgressItem.ProtoReflect.Descriptor instead.
func (*ProgressItem) Descriptor() ([]byte, []int) {
	return file_core_v1_problem_problem_proto_rawDescGZIP(), []int{14}
}

func (x *ProgressItem) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ProgressItem) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type FailedProblem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Platform      string                 `protobuf:"bytes,2,opt,name=platform,proto3" json:"platform,omitempty"`
	ExternalId    string                 `protobuf:"bytes,3,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,5,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	FetchAttempts int32                  `protobuf:"varint,8,opt,name=fetch_attempts,json=fetchAttempts,proto3" json:"fetch_attempts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FailedProblem) Reset() {
	*x = FailedProblem{}
	mi := &file_core_v1_problem_problem_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FailedProblem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailedProblem) ProtoMessage() {}

func (x *FailedProblem) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_problem_problem_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FailedProblem.ProtoReflect.Descriptor instead.
func (*FailedProblem) Descriptor() ([]byte, []int) {
	return file_core_v1_problem_problem_proto_rawDescGZIP(), []int{15}
}

func (x *FailedProblem) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FailedProblem) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *FailedProblem) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *FailedProblem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *FailedProblem) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *FailedProblem) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *FailedProblem) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *FailedProblem) GetFetchAttempts() int32 {
	if x != nil {
		return x.FetchAttempts
	}
	return 0
}

type ActiveJob struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProblemId     uint32                 `protobuf:"varint,1,opt,name=problem_id,json=problemId,proto3" json:"problem_id,omitempty"`
	Platform      string                 `protobuf:"bytes,2,opt,name=platform,proto3" json:"platform,omitempty"`
	ExternalId    string                 `protobuf:"bytes,3,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Stage         string                 `protobuf:"bytes,5,opt,name=stage,proto3" json:"stage,omitempty"` // fetch | analyze
	StartedAt     int64                  `protobuf:"varint,6,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActiveJob) Reset() {
	*x = ActiveJob{}
	mi := &file_core_v1_problem_problem_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActiveJob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActiveJob) ProtoMessage() {}

func (x *ActiveJob) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_problem_problem_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActiveJob.ProtoReflect.Descriptor instead.
func (*ActiveJob) Descriptor() ([]byte, []int) {
	return file_core_v1_problem_problem_proto_rawDescGZIP(), []int{16}
}

func (x *ActiveJob) GetProblemId() uint32 {
	if x != nil {
		return x.ProblemId
	}
	return 0
}

func (x *ActiveJob) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *ActiveJob) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *ActiveJob) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ActiveJob) GetStage() string {
	if x != nil {
		return x.Stage
	}
	return ""
}

func (x *ActiveJob) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

type QueueStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Messages      int64                  `protobuf:"varint,2,opt,name=messages,proto3" json:"messages,omitempty"` // 积压消息数
	Consumers     int64                  `protobuf:"varint,3,opt,name=consumers,proto3" json:"consumers,omitempty"`
	Concurrency   int64                  `protobuf:"varint,4,opt,name=concurrency,proto3" json:"concurrency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueStatus) Reset() {
	*x = QueueStatus{}
	mi := &file_core_v1_problem_problem_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueStatus) ProtoMessage() {}

func (x *QueueStatus) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_problem_problem_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueStatus.ProtoReflect.Descriptor instead.
func (*QueueStatus) Descriptor() ([]byte, []int) {
	return file_core_v1_problem_problem_proto_rawDescGZIP(), []int{17}
}

func (x *QueueStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *QueueStatus) GetMessages() int64 {
	if x != nil {
		return x.Messages
	}
	return 0
}

func (x *QueueStatus) GetConsumers() int64 {
	if x != nil {
		return x.Consumers
	}
	return 0
}

func (x *QueueStatus) GetConcurrency() int64 {
	if x != nil {
		return x.Concurrency
	}
	return 0
}

type ProgressRes struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Code             int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message          string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Items            []*ProgressItem        `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	RecentFailed     []*FailedProblem       `protobuf:"bytes,4,rep,name=recent_failed,json=recentFailed,proto3" json:"recent_failed,omitempty"`
	Total            int64                  `protobuf:"varint,5,opt,name=total,proto3" json:"total,omitempty"`
	Paused           bool                   `protobuf:"varint,6,opt,name=paused,proto3" json:"paused,omitempty"` // AI 暂停（兼容）
	ActiveJobs       []*ActiveJob           `protobuf:"bytes,7,rep,name=active_jobs,json=activeJobs,proto3" json:"active_jobs,omitempty"`
	Queues           []*QueueStatus         `protobuf:"bytes,8,rep,name=queues,proto3" json:"queues,omitempty"`
	InProgress       []*FailedProblem       `protobuf:"bytes,9,rep,name=in_progress,json=inProgress,proto3" json:"in_progress,omitempty"` // DB 中 FETCHING/TAGGING
	FetchPaused      bool                   `protobuf:"varint,10,opt,name=fetch_paused,json=fetchPaused,proto3" json:"fetch_paused,omitempty"`
	AnalyzePaused    bool                   `protobuf:"varint,11,opt,name=analyze_paused,json=analyzePaused,proto3" json:"analyze_paused,omitempty"`
	RecentFailedPerm []*FailedProblem       `protobuf:"bytes,12,rep,name=recent_failed_perm,json=recentFailedPerm,proto3" json:"recent_failed_perm,omitempty"` // 永久失败，可点进详情
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ProgressRes) Reset() {
	*x = ProgressRes{}
	mi := &file_core_v1_problem_problem_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgressRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgressRes) ProtoMessage() {}

func (x *ProgressRes) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_problem_problem_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgressRes.ProtoReflect.Descriptor instead.
func (*ProgressRes) Descriptor() ([]byte, []int) {
	return file_core_v1_problem_problem_proto_rawDescGZIP(), []int{18}
}

func (x *ProgressRes) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ProgressRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ProgressRes) GetItems() []*ProgressItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ProgressRes) GetRecentFailed() []*FailedProblem {
	if x != nil {
		return x.RecentFailed
	}
	return nil
}

func (x *ProgressRes) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ProgressRes) GetPaused() bool {
	if x != nil {
		return x.Paused
	}
	return false
}

func (x *ProgressRes) GetActiveJobs() []*ActiveJob {
	if x != nil {
		return x.ActiveJobs
	}
	return nil
}

func (x *ProgressRes) GetQueues() []*QueueStatus {
	if x != nil {
		return x.Queues
	}
	return nil
}

func (x *ProgressRes) GetInProgress() []*FailedProblem {
	if x != nil {
		return x.InProgress
	}
	return nil
}

func (x *ProgressRes) GetFetchPaused() bool {
	if x != nil {
		return x.FetchPaused
	}
	return false
}

func (x *ProgressRes) GetAnalyzePaused() bool {
	if x != nil {
		return x.AnalyzePaused
	}
	return false
}

func (x *ProgressRes) GetRecentFailedPerm() []*FailedProblem {
	if x != nil {
		return x.RecentFailedPerm
	}
	return nil
}

type BackfillReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 最大处理条数，0 表示默认 500
	Limit         int64 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackfillReq) Reset() {
	*x = BackfillReq{}
	mi := &file_core_v1_problem_problem_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackfillReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackfillReq) ProtoMessage() {}

func (x *BackfillReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_problem_problem_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackfillReq.ProtoReflect.Descriptor instead.
func (*BackfillReq) Descriptor() ([]byte, []int) {
	return file_core_v1_problem_problem_proto_rawDescGZIP(), []int{19}
}

func (x *BackfillReq) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type BackfillRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Scanned       int64                  `protobuf:"varint,3,opt,name=scanned,proto3" json:"scanned,omitempty"`
	Bound         int64                  `protobuf:"varint,4,opt,name=bound,proto3" json:"bound,omitempty"`
	Created       int64                  `protobuf:"varint,5,opt,name=created,proto3" json:"created,omitempty"`
	Enqueued      int64                  `protobuf:"varint,6,opt,name=enqueued,proto3" json:"enqueued,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackfillRes) Reset() {
	*x = BackfillRes{}
	mi := &file_core_v1_problem_problem_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackfillRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackfillRes) ProtoMessage() {}

func (x *BackfillRes) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_problem_problem_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackfillRes.ProtoReflect.Descriptor instead.
func (*BackfillRes) Descriptor() ([]byte, []int) {
	return file_core_v1_problem_problem_proto_rawDescGZIP(), []int{20}
}

func (x *BackfillRes) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *BackfillRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *BackfillRes) GetScanned() int64 {
	if x != nil {
		return x.Scanned
	}
	return 0
}

func (x *BackfillRes) GetBound() int64 {
	if x != nil {
		return x.Bound
	}
	return 0
}

func (x *BackfillRes) GetCreated() int64 {
	if x != nil {
		return x.Created
	}
	return 0
}

func (x *BackfillRes) GetEnqueued() int64 {
	if x != nil {
		return x.Enqueued
	}
	return 0
}

type EmergencyStopReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmergencyStopReq) Reset() {
	*x = EmergencyStopReq{}
	mi := &file_core_v1_problem_problem_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmergencyStopReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmergencyStopReq) ProtoMessage() {}

func (x *EmergencyStopReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_problem_problem_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmergencyStopReq.ProtoReflect.Descriptor instead.
func (*EmergencyStopReq) Descriptor() ([]byte, []int) {
	return file_core_v1_problem_problem_proto_rawDescGZIP(), []int{21}
}

type EmergencyStopRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	PurgedFetch   int64                  `protobuf:"varint,3,opt,name=purged_fetch,json=purgedFetch,proto3" json:"purged_fetch,omitempty"`
	PurgedAnalyze int64                  `protobuf:"varint,4,opt,name=purged_analyze,json=purgedAnalyze,proto3" json:"purged_analyze,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmergencyStopRes) Reset() {
	*x = EmergencyStopRes{}
	mi := &file_core_v1_problem_problem_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmergencyStopRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmergencyStopRes) ProtoMessage() {}

func (x *EmergencyStopRes) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_problem_problem_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmergencyStopRes.ProtoReflect.Descriptor instead.
func (*EmergencyStopRes) Descriptor() ([]byte, []int) {
	return file_core_v1_problem_problem_proto_rawDescGZIP(), []int{22}
}

func (x *EmergencyStopRes) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *EmergencyStopRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *EmergencyStopRes) GetPurgedFetch() int64 {
	if x != nil {
		return x.PurgedFetch
	}
	return 0
}

func (x *EmergencyStopRes) GetPurgedAnalyze() int64 {
	if x != nil {
		return x.PurgedAnalyze
	}
	return 0
}

type ResetAllReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 是否重新入队爬取；false 表示只重置状态并清空队列
	Requeue bool `protobuf:"varint,1,opt,name=requeue,proto3" json:"requeue,omitempty"`
	// 兼容 proto3 默认值：true 时使用 requeue 字段，false 时默认 requeue=true
	RequeueSet    bool `protobuf:"varint,2,opt,name=requeue_set,json=requeueSet,proto3" json:"requeue_set,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetAllReq) Reset() {
	*x = ResetAllReq{}
	mi := &file_core_v1_problem_problem_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetAllReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetAllReq) ProtoMessage() {}

func (x *ResetAllReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_problem_problem_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetAllReq.ProtoReflect.Descriptor instead.
func (*ResetAllReq) Descriptor() ([]byte, []int) {
	return file_core_v1_problem_problem_proto_rawDescGZIP(), []int{23}
}

func (x *ResetAllReq) GetRequeue() bool {
	if x != nil {
		return x.Requeue
	}
	return false
}

func (x *ResetAllReq) GetRequeueSet() bool {
	if x != nil {
		return x.RequeueSet
	}
	return false
}

type ResetAllRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Reset_        int64                  `protobuf:"varint,3,opt,name=reset,proto3" json:"reset,omitempty"`
	Enqueued      int64                  `protobuf:"varint,4,opt,name=enqueued,proto3" json:"enqueued,omitempty"`
	PurgedFetch   int64                  `protobuf:"varint,5,opt,name=purged_fetch,json=purgedFetch,proto3" json:"purged_fetch,omitempty"`
	PurgedAnalyze int64                  `protobuf:"varint,6,opt,name=purged_analyze,json=purgedAnalyze,proto3" json:"purged_analyze,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetAllRes) Reset() {
	*x = ResetAllRes{}
	mi := &file_core_v1_problem_problem_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetAllRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetAllRes) ProtoMessage() {}

func (x *ResetAllRes) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_problem_problem_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetAllRes.ProtoReflect.Descriptor instead.
func (*ResetAllRes) Descriptor() ([]byte, []int) {
	return file_core_v1_problem_problem_proto_rawDescGZIP(), []int{24}
}

func (x *ResetAllRes) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ResetAllRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ResetAllRes) GetReset_() int64 {
	if x != nil {
		return x.Reset_
	}
	return 0
}

func (x *ResetAllRes) GetEnqueued() int64 {
	if x != nil {
		return x.Enqueued
	}
	return 0
}

func (x *ResetAllRes) GetPurgedFetch() int64 {
	if x != nil {
		return x.PurgedFetch
	}
	return 0
}

func (x *ResetAllRes) GetPurgedAnalyze() int64 {
	if x != nil {
		return x.PurgedAnalyze
	}
	return 0
}

type ResumeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeReq) Reset() {
	*x = ResumeReq{}
	mi := &file_core_v1_problem_problem_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeReq) ProtoMessage() {}

func (x *ResumeReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_problem_problem_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeReq.ProtoReflect.Descriptor instead.
func (*ResumeReq) Descriptor() ([]byte, []int) {
	return file_core_v1_problem_problem_proto_rawDescGZIP(), []int{25}
}

type ResumeRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeRes) Reset() {
	*x = ResumeRes{}
	mi := &file_core_v1_problem_problem_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeRes) ProtoMessage() {}

func (x *ResumeRes) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_problem_problem_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeRes.ProtoReflect.Descriptor instead.
func (*ResumeRes) Descriptor() ([]byte, []int) {
	return file_core_v1_problem_problem_proto_rawDescGZIP(), []int{26}
}

func (x *ResumeRes) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ResumeRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RetryFailedReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 最大重试条数，0 表示不限制
	Limit         int64 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetryFailedReq) Reset() {
	*x = RetryFailedReq{}
	mi := &file_core_v1_problem_problem_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryFailedReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryFailedReq) ProtoMessage() {}

func (x *RetryFailedReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_problem_problem_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryFailedReq.ProtoReflect.Descriptor instead.
func (*RetryFailedReq) Descriptor() ([]byte, []int) {
	return file_core_v1_problem_problem_proto_rawDescGZIP(), []int{27}
}

func (x *RetryFailedReq) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type RetryFailedRes struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Code    int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// 扫描到的 FAILED 数
	Scanned int64 `protobuf:"varint,3,opt,name=scanned,proto3" json:"scanned,omitempty"`
	// 成功入队数
	Enqueued int64 `protobuf:"varint,4,opt,name=enqueued,proto3" json:"enqueued,omitempty"`
	// 升为 FAILED_PERM（黑名单）的数量
	Blacklisted   int64 `protobuf:"varint,5,opt,name=blacklisted,proto3" json:"blacklisted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetryFailedRes) Reset() {
	*x = RetryFailedRes{}
	mi := &file_core_v1_problem_problem_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryFailedRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryFailedRes) ProtoMessage() {}

func (x *RetryFailedRes) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_problem_problem_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryFailedRes.ProtoReflect.Descriptor instead.
func (*RetryFailedRes) Descriptor() ([]byte, []int) {
	return file_core_v1_problem_problem_proto_rawDescGZIP(), []int{28}
}

func (x *RetryFailedRes) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *RetryFailedRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RetryFailedRes) GetScanned() int64 {
	if x != nil {
		return x.Scanned
	}
	return 0
}

func (x *RetryFailedRes) GetEnqueued() int64 {
	if x != nil {
		return x.Enqueued
	}
	return 0
}

func (x *RetryFailedRes) GetBlacklisted() int64 {
	if x != nil {
		return x.Blacklisted
	}
	return 0
}

// pause=true 暂停并清队列；pause=false 恢复；未设置时按当前状态翻转
type TogglePipelineReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pause         bool                   `protobuf:"varint,1,opt,name=pause,proto3" json:"pause,omitempty"`
	PauseSet      bool                   `protobuf:"varint,2,opt,name=pause_set,json=pauseSet,proto3" json:"pause_set,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TogglePipelineReq) Reset() {
	*x = TogglePipelineReq{}
	mi := &file_core_v1_problem_problem_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TogglePipelineReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TogglePipelineReq) ProtoMessage() {}

func (x *TogglePipelineReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_problem_problem_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TogglePipelineReq.ProtoReflect.Descriptor instead.
func (*TogglePipelineReq) Descriptor() ([]byte, []int) {
	return file_core_v1_problem_problem_proto_rawDescGZIP(), []int{29}
}

func (x *TogglePipelineReq) GetPause() bool {
	if x != nil {
		return x.Pause
	}
	return false
}

func (x *TogglePipelineReq) GetPauseSet() bool {
	if x != nil {
		return x.PauseSet
	}
	return false
}

type TogglePipelineRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Paused        bool                   `protobuf:"varint,3,opt,name=paused,proto3" json:"paused,omitempty"`
	Purged        int64                  `protobuf:"varint,4,opt,name=purged,proto3" json:"purged,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TogglePipelineRes) Reset() {
	*x = TogglePipelineRes{}
	mi := &file_core_v1_problem_problem_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TogglePipelineRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TogglePipelineRes) ProtoMessage() {}

func (x *TogglePipelineRes) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_problem_problem_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TogglePipelineRes.ProtoReflect.Descriptor instead.
func (*TogglePipelineRes) Descriptor() ([]byte, []int) {
	return file_core_v1_problem_problem_proto_rawDescGZIP(), []int{30}
}

func (x *TogglePipelineRes) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *TogglePipelineRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TogglePipelineRes) GetPaused() bool {
	if x != nil {
		return x.Paused
	}
	return false
}

func (x *TogglePipelineRes) GetPurged() int64 {
	if x != nil {
		return x.Purged
	}
	return 0
}

var File_core_v1_problem_problem_proto protoreflect.FileDescriptor

const file_core_v1_problem_problem_proto_rawDesc = "" +
	"\n" +
	"\x1dcore/v1/problem/problem.proto\x12\x13api.core.v1.problem\x1a\x1cgoogle/api/annotations.proto\"\xa3\x01\n" +
	"\fSolutionMeta\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12'\n" +
	"\x0ftime_complexity\x18\x02 \x01(\tR\x0etimeComplexity\x12)\n" +
	"\x10space_complexity\x18\x03 \x01(\tR\x0fspaceComplexity\x12+\n" +
	"\x11brief_explanation\x18\x04 \x01(\tR\x10briefExplanation\"\xbb\x03\n" +
	"\vProblemInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1a\n" +
	"\bplatform\x18\x02 \x01(\tR\bplatform\x12\x1f\n" +
	"\vexternal_id\x18\x03 \x01(\tR\n" +
	"externalId\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x10\n" +
	"\x03url\x18\x05 \x01(\tR\x03url\x12\x1d\n" +
	"\n" +
	"content_md\x18\x06 \x01(\tR\tcontentMd\x12!\n" +
	"\fproblem_type\x18\a \x01(\tR\vproblemType\x12\x12\n" +
	"\x04tags\x18\b \x03(\tR\x04tags\x12?\n" +
	"\tsolutions\x18\t \x03(\v2!.api.core.v1.problem.SolutionMetaR\tsolutions\x12\x1e\n" +
	"\n" +
	"difficulty\x18\n" +
	" \x01(\tR\n" +
	"difficulty\x12\x16\n" +
	"\x06status\x18\v \x01(\tR\x06status\x12\x1b\n" +
	"\terror_msg\x18\f \x01(\tR\berrorMsg\x12*\n" +
	"\x11last_submitted_at\x18\r \x01(\x03R\x0flastSubmittedAt\x12\x1f\n" +
	"\vuser_status\x18\x0e \x01(\tR\n" +
	"userStatus\"\xfb\x01\n" +
	"\x0eListProblemReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x03R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x03R\bpageSize\x12\x12\n" +
	"\x04sort\x18\x03 \x01(\tR\x04sort\x12\x1c\n" +
	"\tplatforms\x18\x04 \x01(\tR\tplatforms\x12\x12\n" +
	"\x04tags\x18\x05 \x01(\tR\x04tags\x12\x1f\n" +
	"\vuser_status\x18\x06 \x01(\tR\n" +
	"userStatus\x12\x17\n" +
	"\auser_id\x18\a \x01(\x03R\x06userId\x12\x18\n" +
	"\akeyword\x18\b \x01(\tR\akeyword\x12\x1e\n" +
	"\n" +
	"difficulty\x18\t \x01(\tR\n" +
	"difficulty\"\xbb\x01\n" +
	"\x0eListProblemRes\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x124\n" +
	"\x04data\x18\x03 \x03(\v2 .api.core.v1.problem.ProblemInfoR\x04data\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x03R\x05total\x12\x12\n" +
	"\x04page\x18\x05 \x01(\x03R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x06 \x01(\x03R\bpageSize\"\x1f\n" +
	"\rGetProblemReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"s\n" +
	"\rGetProblemRes\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x124\n" +
	"\x04data\x18\x03 \x01(\v2 .api.core.v1.problem.ProblemInfoR\x04data\"\xe9\x01\n" +
	"\x0eSubmissionInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x1a\n" +
	"\bplatform\x18\x03 \x01(\tR\bplatform\x12\x1b\n" +
	"\tsubmit_id\x18\x04 \x01(\tR\bsubmitId\x12\x12\n" +
	"\x04lang\x18\x05 \x01(\tR\x04lang\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x12\n" +
	"\x04time\x18\a \x01(\x03R\x04time\x12\x18\n" +
	"\acontest\x18\b \x01(\tR\acontest\x12\x1b\n" +
	"\tuser_name\x18\t \x01(\tR\buserName\"}\n" +
	"\x12ListSubmissionsReq\x12\x1d\n" +
	"\n" +
	"problem_id\x18\x01 \x01(\rR\tproblemId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x03R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x03R\bpageSize\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\x03R\x06userId\"\x91\x01\n" +
	"\x12ListSubmissionsRes\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x127\n" +
	"\x04data\x18\x03 \x03(\v2#.api.core.v1.problem.SubmissionInfoR\x04data\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x03R\x05total\"M\n" +
	"\bTagScore\x12\x10\n" +
	"\x03tag\x18\x01 \x01(\tR\x03tag\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x01R\x05score\x12\x19\n" +
	"\bac_count\x18\x03 \x01(\x03R\aacCount\"6\n" +
	"\n" +
	"NamedCount\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\")\n" +
	"\x0eUserProfileReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"\x92\x02\n" +
	"\x0eUserProfileRes\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x123\n" +
	"\x05radar\x18\x03 \x03(\v2\x1d.api.core.v1.problem.TagScoreR\x05radar\x12=\n" +
	"\tplatforms\x18\x04 \x03(\v2\x1f.api.core.v1.problem.NamedCountR\tplatforms\x12C\n" +
	"\fdifficulties\x18\x05 \x03(\v2\x1f.api.core.v1.problem.NamedCountR\fdifficulties\x12\x19\n" +
	"\btotal_ac\x18\x06 \x01(\x03R\atotalAc\"\r\n" +
	"\vProgressReq\"<\n" +
	"\fProgressItem\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\"\xed\x01\n" +
	"\rFailedProblem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1a\n" +
	"\bplatform\x18\x02 \x01(\tR\bplatform\x12\x1f\n" +
	"\vexternal_id\x18\x03 \x01(\tR\n" +
	"externalId\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x1b\n" +
	"\terror_msg\x18\x05 \x01(\tR\berrorMsg\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\x03R\tupdatedAt\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12%\n" +
	"\x0efetch_attempts\x18\b \x01(\x05R\rfetchAttempts\"\xb2\x01\n" +
	"\tActiveJob\x12\x1d\n" +
	"\n" +
	"problem_id\x18\x01 \x01(\rR\tproblemId\x12\x1a\n" +
	"\bplatform\x18\x02 \x01(\tR\bplatform\x12\x1f\n" +
	"\vexternal_id\x18\x03 \x01(\tR\n" +
	"externalId\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x14\n" +
	"\x05stage\x18\x05 \x01(\tR\x05stage\x12\x1d\n" +
	"\n" +
	"started_at\x18\x06 \x01(\x03R\tstartedAt\"}\n" +
	"\vQueueStatus\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bmessages\x18\x02 \x01(\x03R\bmessages\x12\x1c\n" +
	"\tconsumers\x18\x03 \x01(\x03R\tconsumers\x12 \n" +
	"\vconcurrency\x18\x04 \x01(\x03R\vconcurrency\"\xc7\x04\n" +
	"\vProgressRes\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x127\n" +
	"\x05items\x18\x03 \x03(\v2!.api.core.v1.problem.ProgressItemR\x05items\x12G\n" +
	"\rrecent_failed\x18\x04 \x03(\v2\".api.core.v1.problem.FailedProblemR\frecentFailed\x12\x14\n" +
	"\x05total\x18\x05 \x01(\x03R\x05total\x12\x16\n" +
	"\x06paused\x18\x06 \x01(\bR\x06paused\x12?\n" +
	"\vactive_jobs\x18\a \x03(\v2\x1e.api.core.v1.problem.ActiveJobR\n" +
	"activeJobs\x128\n" +
	"\x06queues\x18\b \x03(\v2 .api.core.v1.problem.QueueStatusR\x06queues\x12C\n" +
	"\vin_progress\x18\t \x03(\v2\".api.core.v1.problem.FailedProblemR\n" +
	"inProgress\x12!\n" +
	"\ffetch_paused\x18\n" +
	" \x01(\bR\vfetchPaused\x12%\n" +
	"\x0eanalyze_paused\x18\v \x01(\bR\ranalyzePaused\x12P\n" +
	"\x12recent_failed_perm\x18\f \x03(\v2\".api.core.v1.problem.FailedProblemR\x10recentFailedPerm\"#\n" +
	"\vBackfillReq\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x03R\x05limit\"\xa1\x01\n" +
	"\vBackfillRes\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x18\n" +
	"\ascanned\x18\x03 \x01(\x03R\ascanned\x12\x14\n" +
	"\x05bound\x18\x04 \x01(\x03R\x05bound\x12\x18\n" +
	"\acreated\x18\x05 \x01(\x03R\acreated\x12\x1a\n" +
	"\benqueued\x18\x06 \x01(\x03R\benqueued\"\x12\n" +
	"\x10EmergencyStopReq\"\x8a\x01\n" +
	"\x10EmergencyStopRes\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12!\n" +
	"\fpurged_fetch\x18\x03 \x01(\x03R\vpurgedFetch\x12%\n" +
	"\x0epurged_analyze\x18\x04 \x01(\x03R\rpurgedAnalyze\"H\n" +
	"\vResetAllReq\x12\x18\n" +
	"\arequeue\x18\x01 \x01(\bR\arequeue\x12\x1f\n" +
	"\vrequeue_set\x18\x02 \x01(\bR\n" +
	"requeueSet\"\xb7\x01\n" +
	"\vResetAllRes\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x14\n" +
	"\x05reset\x18\x03 \x01(\x03R\x05reset\x12\x1a\n" +
	"\benqueued\x18\x04 \x01(\x03R\benqueued\x12!\n" +
	"\fpurged_fetch\x18\x05 \x01(\x03R\vpurgedFetch\x12%\n" +
	"\x0epurged_analyze\x18\x06 \x01(\x03R\rpurgedAnalyze\"\v\n" +
	"\tResumeReq\"9\n" +
	"\tResumeRes\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"&\n" +
	"\x0eRetryFailedReq\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x03R\x05limit\"\x96\x01\n" +
	"\x0eRetryFailedRes\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x18\n" +
	"\ascanned\x18\x03 \x01(\x03R\ascanned\x12\x1a\n" +
	"\benqueued\x18\x04 \x01(\x03R\benqueued\x12 \n" +
	"\vblacklisted\x18\x05 \x01(\x03R\vblacklisted\"F\n" +
	"\x11TogglePipelineReq\x12\x14\n" +
	"\x05pause\x18\x01 \x01(\bR\x05pause\x12\x1b\n" +
	"\tpause_set\x18\x02 \x01(\bR\bpauseSet\"q\n" +
	"\x11TogglePipelineRes\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x16\n" +
	"\x06paused\x18\x03 \x01(\bR\x06paused\x12\x16\n" +
	"\x06purged\x18\x04 \x01(\x03R\x06purged2\xe9\v\n" +
	"\aProblem\x12o\n" +
	"\x04List\x12#.api.core.v1.problem.ListProblemReq\x1a#.api.core.v1.problem.ListProblemRes\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/v1/core/problem/list\x12k\n" +
	"\x03Get\x12\".api.core.v1.problem.GetProblemReq\x1a\".api.core.v1.problem.GetProblemRes\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/v1/core/problem/get\x12\x89\x01\n" +
	"\x0fListSubmissions\x12'.api.core.v1.problem.ListSubmissionsReq\x1a'.api.core.v1.problem.ListSubmissionsRes\"$\x82\xd3\xe4\x93\x02\x1e\x12\x1c/v1/core/problem/submissions\x12~\n" +
	"\vUserProfile\x12#.api.core.v1.problem.UserProfileReq\x1a#.api.core.v1.problem.UserProfileRes\"%\x82\xd3\xe4\x93\x02\x1f\x12\x1d/v1/core/problem/user-profile\x12q\n" +
	"\bProgress\x12 .api.core.v1.problem.ProgressReq\x1a .api.core.v1.problem.ProgressRes\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/v1/core/problem/progress\x12t\n" +
	"\bBackfill\x12 .api.core.v1.problem.BackfillReq\x1a .api.core.v1.problem.BackfillRes\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/v1/core/problem/backfill\x12\x89\x01\n" +
	"\rEmergencyStop\x12%.api.core.v1.problem.EmergencyStopReq\x1a%.api.core.v1.problem.EmergencyStopRes\"*\x82\xd3\xe4\x93\x02$:\x01*\"\x1f/v1/core/problem/emergency-stop\x12u\n" +
	"\bResetAll\x12 .api.core.v1.problem.ResetAllReq\x1a .api.core.v1.problem.ResetAllRes\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/v1/core/problem/reset-all\x12l\n" +
	"\x06Resume\x12\x1e.api.core.v1.problem.ResumeReq\x1a\x1e.api.core.v1.problem.ResumeRes\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/v1/core/problem/resume\x12\x81\x01\n" +
	"\vRetryFailed\x12#.api.core.v1.problem.RetryFailedReq\x1a#.api.core.v1.problem.RetryFailedRes\"(\x82\xd3\xe4\x93\x02\":\x01*\"\x1d/v1/core/problem/retry-failed\x12\x8b\x01\n" +
	"\rToggleAnalyze\x12&.api.core.v1.problem.TogglePipelineReq\x1a&.api.core.v1.problem.TogglePipelineRes\"*\x82\xd3\xe4\x93\x02$:\x01*\"\x1f/v1/core/problem/toggle-analyze\x12\x87\x01\n" +
	"\vToggleFetch\x12&.api.core.v1.problem.TogglePipelineReq\x1a&.api.core.v1.problem.TogglePipelineRes\"(\x82\xd3\xe4\x93\x02\":\x01*\"\x1d/v1/core/problem/toggle-fetchB>\n" +
	"\x13api.core.v1.problemP\x01Z%cwxu-algo/api/core/v1/problem;problemb\x06proto3"

var (
	file_core_v1_problem_problem_proto_rawDescOnce sync.Once
	file_core_v1_problem_problem_proto_rawDescData []byte
)

func file_core_v1_problem_problem_proto_rawDescGZIP() []byte {
	file_core_v1_problem_problem_proto_rawDescOnce.Do(func() {
		file_core_v1_problem_problem_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_v1_problem_problem_proto_rawDesc), len(file_core_v1_problem_problem_proto_rawDesc)))
	})
	return file_core_v1_problem_problem_proto_rawDescData
}

var file_core_v1_problem_problem_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_core_v1_problem_problem_proto_goTypes = []any{
	(*SolutionMeta)(nil),       // 0: api.core.v1.problem.SolutionMeta
	(*ProblemInfo)(nil),        // 1: api.core.v1.problem.ProblemInfo
	(*ListProblemReq)(nil),     // 2: api.core.v1.problem.ListProblemReq
	(*ListProblemRes)(nil),     // 3: api.core.v1.problem.ListProblemRes
	(*GetProblemReq)(nil),      // 4: api.core.v1.problem.GetProblemReq
	(*GetProblemRes)(nil),      // 5: api.core.v1.problem.GetProblemRes
	(*SubmissionInfo)(nil),     // 6: api.core.v1.problem.SubmissionInfo
	(*ListSubmissionsReq)(nil), // 7: api.core.v1.problem.ListSubmissionsReq
	(*ListSubmissionsRes)(nil), // 8: api.core.v1.problem.ListSubmissionsRes
	(*TagScore)(nil),           // 9: api.core.v1.problem.TagScore
	(*NamedCount)(nil),         // 10: api.core.v1.problem.NamedCount
	(*UserProfileReq)(nil),     // 11: api.core.v1.problem.UserProfileReq
	(*UserProfileRes)(nil),     // 12: api.core.v1.problem.UserProfileRes
	(*ProgressReq)(nil),        // 13: api.core.v1.problem.ProgressReq
	(*ProgressItem)(nil),       // 14: api.core.v1.problem.ProgressItem
	(*FailedProblem)(nil),      // 15: api.core.v1.problem.FailedProblem
	(*ActiveJob)(nil),          // 16: api.core.v1.problem.ActiveJob
	(*QueueStatus)(nil),        // 17: api.core.v1.problem.QueueStatus
	(*ProgressRes)(nil),        // 18: api.core.v1.problem.ProgressRes
	(*BackfillReq)(nil),        // 19: api.core.v1.problem.BackfillReq
	(*BackfillRes)(nil),        // 20: api.core.v1.problem.BackfillRes
	(*EmergencyStopReq)(nil),   // 21: api.core.v1.problem.EmergencyStopReq
	(*EmergencyStopRes)(nil),   // 22: api.core.v1.problem.EmergencyStopRes
	(*ResetAllReq)(nil),        // 23: api.core.v1.problem.ResetAllReq
	(*ResetAllRes)(nil),        // 24: api.core.v1.problem.ResetAllRes
	(*ResumeReq)(nil),          // 25: api.core.v1.problem.ResumeReq
	(*ResumeRes)(nil),          // 26: api.core.v1.problem.ResumeRes
	(*RetryFailedReq)(nil),     // 27: api.core.v1.problem.RetryFailedReq
	(*RetryFailedRes)(nil),     // 28: api.core.v1.problem.RetryFailedRes
	(*TogglePipelineReq)(nil),  // 29: api.core.v1.problem.TogglePipelineReq
	(*TogglePipelineRes)(nil),  // 30: api.core.v1.problem.TogglePipelineRes
}
var file_core_v1_problem_problem_proto_depIdxs = []int32{
	0,  // 0: api.core.v1.problem.ProblemInfo.solutions:type_name -> api.core.v1.problem.SolutionMeta
	1,  // 1: api.core.v1.problem.ListProblemRes.data:type_name -> api.core.v1.problem.ProblemInfo
	1,  // 2: api.core.v1.problem.GetProblemRes.data:type_name -> api.core.v1.problem.ProblemInfo
	6,  // 3: api.core.v1.problem.ListSubmissionsRes.data:type_name -> api.core.v1.problem.SubmissionInfo
	9,  // 4: api.core.v1.problem.UserProfileRes.radar:type_name -> api.core.v1.problem.TagScore
	10, // 5: api.core.v1.problem.UserProfileRes.platforms:type_name -> api.core.v1.problem.NamedCount
	10, // 6: api.core.v1.problem.UserProfileRes.difficulties:type_name -> api.core.v1.problem.NamedCount
	14, // 7: api.core.v1.problem.ProgressRes.items:type_name -> api.core.v1.problem.ProgressItem
	15, // 8: api.core.v1.problem.ProgressRes.recent_failed:type_name -> api.core.v1.problem.FailedProblem
	16, // 9: api.core.v1.problem.ProgressRes.active_jobs:type_name -> api.core.v1.problem.ActiveJob
	17, // 10: api.core.v1.problem.ProgressRes.queues:type_name -> api.core.v1.problem.QueueStatus
	15, // 11: api.core.v1.problem.ProgressRes.in_progress:type_name -> api.core.v1.problem.FailedProblem
	15, // 12: api.core.v1.problem.ProgressRes.recent_failed_perm:type_name -> api.core.v1.problem.FailedProblem
	2,  // 13: api.core.v1.problem.Problem.List:input_type -> api.core.v1.problem.ListProblemReq
	4,  // 14: api.core.v1.problem.Problem.Get:input_type -> api.core.v1.problem.GetProblemReq
	7,  // 15: api.core.v1.problem.Problem.ListSubmissions:input_type -> api.core.v1.problem.ListSubmissionsReq
	11, // 16: api.core.v1.problem.Problem.UserProfile:input_type -> api.core.v1.problem.UserProfileReq
	13, // 17: api.core.v1.problem.Problem.Progress:input_type -> api.core.v1.problem.ProgressReq
	19, // 18: api.core.v1.problem.Problem.Backfill:input_type -> api.core.v1.problem.BackfillReq
	21, // 19: api.core.v1.problem.Problem.EmergencyStop:input_type -> api.core.v1.problem.EmergencyStopReq
	23, // 20: api.core.v1.problem.Problem.ResetAll:input_type -> api.core.v1.problem.ResetAllReq
	25, // 21: api.core.v1.problem.Problem.Resume:input_type -> api.core.v1.problem.ResumeReq
	27, // 22: api.core.v1.problem.Problem.RetryFailed:input_type -> api.core.v1.problem.RetryFailedReq
	29, // 23: api.core.v1.problem.Problem.ToggleAnalyze:input_type -> api.core.v1.problem.TogglePipelineReq
	29, // 24: api.core.v1.problem.Problem.ToggleFetch:input_type -> api.core.v1.problem.TogglePipelineReq
	3,  // 25: api.core.v1.problem.Problem.List:output_type -> api.core.v1.problem.ListProblemRes
	5,  // 26: api.core.v1.problem.Problem.Get:output_type -> api.core.v1.problem.GetProblemRes
	8,  // 27: api.core.v1.problem.Problem.ListSubmissions:output_type -> api.core.v1.problem.ListSubmissionsRes
	12, // 28: api.core.v1.problem.Problem.UserProfile:output_type -> api.core.v1.problem.UserProfileRes
	18, // 29: api.core.v1.problem.Problem.Progress:output_type -> api.core.v1.problem.ProgressRes
	20, // 30: api.core.v1.problem.Problem.Backfill:output_type -> api.core.v1.problem.BackfillRes
	22, // 31: api.core.v1.problem.Problem.EmergencyStop:output_type -> api.core.v1.problem.EmergencyStopRes
	24, // 32: api.core.v1.problem.Problem.ResetAll:output_type -> api.core.v1.problem.ResetAllRes
	26, // 33: api.core.v1.problem.Problem.Resume:output_type -> api.core.v1.problem.ResumeRes
	28, // 34: api.core.v1.problem.Problem.RetryFailed:output_type -> api.core.v1.problem.RetryFailedRes
	30, // 35: api.core.v1.problem.Problem.ToggleAnalyze:output_type -> api.core.v1.problem.TogglePipelineRes
	30, // 36: api.core.v1.problem.Problem.ToggleFetch:output_type -> api.core.v1.problem.TogglePipelineRes
	25, // [25:37] is the sub-list for method output_type
	13, // [13:25] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_core_v1_problem_problem_proto_init() }
func file_core_v1_problem_problem_proto_init() {
	if File_core_v1_problem_problem_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_v1_problem_problem_proto_rawDesc), len(file_core_v1_problem_problem_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_core_v1_problem_problem_proto_goTypes,
		DependencyIndexes: file_core_v1_problem_problem_proto_depIdxs,
		MessageInfos:      file_core_v1_problem_problem_proto_msgTypes,
	}.Build()
	File_core_v1_problem_problem_proto = out.File
	file_core_v1_problem_problem_proto_goTypes = nil
	file_core_v1_problem_problem_proto_depIdxs = nil
}
