// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v6.33.1
// source: core/v1/problem/problem.proto

package problem

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationProblemBackfill = "/api.core.v1.problem.Problem/Backfill"
const OperationProblemEmergencyStop = "/api.core.v1.problem.Problem/EmergencyStop"
const OperationProblemGet = "/api.core.v1.problem.Problem/Get"
const OperationProblemList = "/api.core.v1.problem.Problem/List"
const OperationProblemListSubmissions = "/api.core.v1.problem.Problem/ListSubmissions"
const OperationProblemProgress = "/api.core.v1.problem.Problem/Progress"
const OperationProblemResetAll = "/api.core.v1.problem.Problem/ResetAll"
const OperationProblemResume = "/api.core.v1.problem.Problem/Resume"
const OperationProblemRetryFailed = "/api.core.v1.problem.Problem/RetryFailed"
const OperationProblemToggleAnalyze = "/api.core.v1.problem.Problem/ToggleAnalyze"
const OperationProblemToggleFetch = "/api.core.v1.problem.Problem/ToggleFetch"
const OperationProblemUserProfile = "/api.core.v1.problem.Problem/UserProfile"

type ProblemHTTPServer interface {
	Backfill(context.Context, *BackfillReq) (*BackfillRes, error)
	// EmergencyStop 紧急停止：暂停 AI 并清空分析队列（兼容）
	EmergencyStop(context.Context, *EmergencyStopReq) (*EmergencyStopRes, error)
	Get(context.Context, *GetProblemReq) (*GetProblemRes, error)
	List(context.Context, *ListProblemReq) (*ListProblemRes, error)
	ListSubmissions(context.Context, *ListSubmissionsReq) (*ListSubmissionsRes, error)
	Progress(context.Context, *ProgressReq) (*ProgressRes, error)
	// ResetAll 全部重置：清空 AI 标签，保留题面，可选重新入队分析
	ResetAll(context.Context, *ResetAllReq) (*ResetAllRes, error)
	// Resume 恢复 AI（兼容）
	Resume(context.Context, *ResumeReq) (*ResumeRes, error)
	// RetryFailed 重试错误队列：仅重入 FAILED（可重试），排除 FAILED_PERM 黑名单
	RetryFailed(context.Context, *RetryFailedReq) (*RetryFailedRes, error)
	// ToggleAnalyze 暂停/恢复 AI 分析（暂停时清空分析队列）
	ToggleAnalyze(context.Context, *TogglePipelineReq) (*TogglePipelineRes, error)
	// ToggleFetch 暂停/恢复题面爬取（暂停时清空爬取队列）
	ToggleFetch(context.Context, *TogglePipelineReq) (*TogglePipelineRes, error)
	UserProfile(context.Context, *UserProfileReq) (*UserProfileRes, error)
}

func RegisterProblemHTTPServer(s *http.Server, srv ProblemHTTPServer) {
	r := s.Route("/")
	r.GET("/v1/core/problem/list", _Problem_List0_HTTP_Handler(srv))
	r.GET("/v1/core/problem/get", _Problem_Get0_HTTP_Handler(srv))
	r.GET("/v1/core/problem/submissions", _Problem_ListSubmissions0_HTTP_Handler(srv))
	r.GET("/v1/core/problem/user-profile", _Problem_UserProfile0_HTTP_Handler(srv))
	r.GET("/v1/core/problem/progress", _Problem_Progress0_HTTP_Handler(srv))
	r.POST("/v1/core/problem/backfill", _Problem_Backfill0_HTTP_Handler(srv))
	r.POST("/v1/core/problem/emergency-stop", _Problem_EmergencyStop0_HTTP_Handler(srv))
	r.POST("/v1/core/problem/reset-all", _Problem_ResetAll0_HTTP_Handler(srv))
	r.POST("/v1/core/problem/resume", _Problem_Resume0_HTTP_Handler(srv))
	r.POST("/v1/core/problem/retry-failed", _Problem_RetryFailed0_HTTP_Handler(srv))
	r.POST("/v1/core/problem/toggle-analyze", _Problem_ToggleAnalyze0_HTTP_Handler(srv))
	r.POST("/v1/core/problem/toggle-fetch", _Problem_ToggleFetch0_HTTP_Handler(srv))
}

func _Problem_List0_HTTP_Handler(srv ProblemHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListProblemReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProblemList)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.List(ctx, req.(*ListProblemReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListProblemRes)
		return ctx.Result(200, reply)
	}
}

func _Problem_Get0_HTTP_Handler(srv ProblemHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetProblemReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProblemGet)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Get(ctx, req.(*GetProblemReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetProblemRes)
		return ctx.Result(200, reply)
	}
}

func _Problem_ListSubmissions0_HTTP_Handler(srv ProblemHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListSubmissionsReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProblemListSubmissions)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListSubmissions(ctx, req.(*ListSubmissionsReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListSubmissionsRes)
		return ctx.Result(200, reply)
	}
}

func _Problem_UserProfile0_HTTP_Handler(srv ProblemHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UserProfileReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProblemUserProfile)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UserProfile(ctx, req.(*UserProfileReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UserProfileRes)
		return ctx.Result(200, reply)
	}
}

func _Problem_Progress0_HTTP_Handler(srv ProblemHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ProgressReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProblemProgress)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Progress(ctx, req.(*ProgressReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ProgressRes)
		return ctx.Result(200, reply)
	}
}

func _Problem_Backfill0_HTTP_Handler(srv ProblemHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in BackfillReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProblemBackfill)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Backfill(ctx, req.(*BackfillReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*BackfillRes)
		return ctx.Result(200, reply)
	}
}

func _Problem_EmergencyStop0_HTTP_Handler(srv ProblemHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in EmergencyStopReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProblemEmergencyStop)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.EmergencyStop(ctx, req.(*EmergencyStopReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*EmergencyStopRes)
		return ctx.Result(200, reply)
	}
}

func _Problem_ResetAll0_HTTP_Handler(srv ProblemHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ResetAllReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProblemResetAll)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ResetAll(ctx, req.(*ResetAllReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ResetAllRes)
		return ctx.Result(200, reply)
	}
}

func _Problem_Resume0_HTTP_Handler(srv ProblemHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ResumeReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProblemResume)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Resume(ctx, req.(*ResumeReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ResumeRes)
		return ctx.Result(200, reply)
	}
}

func _Problem_RetryFailed0_HTTP_Handler(srv ProblemHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RetryFailedReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProblemRetryFailed)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RetryFailed(ctx, req.(*RetryFailedReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*RetryFailedRes)
		return ctx.Result(200, reply)
	}
}

func _Problem_ToggleAnalyze0_HTTP_Handler(srv ProblemHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in TogglePipelineReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProblemToggleAnalyze)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ToggleAnalyze(ctx, req.(*TogglePipelineReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*TogglePipelineRes)
		return ctx.Result(200, reply)
	}
}

func _Problem_ToggleFetch0_HTTP_Handler(srv ProblemHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in TogglePipelineReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProblemToggleFetch)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ToggleFetch(ctx, req.(*TogglePipelineReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*TogglePipelineRes)
		return ctx.Result(200, reply)
	}
}

type ProblemHTTPClient interface {
	Backfill(ctx context.Context, req *BackfillReq, opts ...http.CallOption) (rsp *BackfillRes, err error)
	// EmergencyStop 紧急停止：暂停 AI 并清空分析队列（兼容）
	EmergencyStop(ctx context.Context, req *EmergencyStopReq, opts ...http.CallOption) (rsp *EmergencyStopRes, err error)
	Get(ctx context.Context, req *GetProblemReq, opts ...http.CallOption) (rsp *GetProblemRes, err error)
	List(ctx context.Context, req *ListProblemReq, opts ...http.CallOption) (rsp *ListProblemRes, err error)
	ListSubmissions(ctx context.Context, req *ListSubmissionsReq, opts ...http.CallOption) (rsp *ListSubmissionsRes, err error)
	Progress(ctx context.Context, req *ProgressReq, opts ...http.CallOption) (rsp *ProgressRes, err error)
	// ResetAll 全部重置：清空 AI 标签，保留题面，可选重新入队分析
	ResetAll(ctx context.Context, req *ResetAllReq, opts ...http.CallOption) (rsp *ResetAllRes, err error)
	// Resume 恢复 AI（兼容）
	Resume(ctx context.Context, req *ResumeReq, opts ...http.CallOption) (rsp *ResumeRes, err error)
	// RetryFailed 重试错误队列：仅重入 FAILED（可重试），排除 FAILED_PERM 黑名单
	RetryFailed(ctx context.Context, req *RetryFailedReq, opts ...http.CallOption) (rsp *RetryFailedRes, err error)
	// ToggleAnalyze 暂停/恢复 AI 分析（暂停时清空分析队列）
	ToggleAnalyze(ctx context.Context, req *TogglePipelineReq, opts ...http.CallOption) (rsp *TogglePipelineRes, err error)
	// ToggleFetch 暂停/恢复题面爬取（暂停时清空爬取队列）
	ToggleFetch(ctx context.Context, req *TogglePipelineReq, opts ...http.CallOption) (rsp *TogglePipelineRes, err error)
	UserProfile(ctx context.Context, req *UserProfileReq, opts ...http.CallOption) (rsp *UserProfileRes, err error)
}

type ProblemHTTPClientImpl struct {
	cc *http.Client
}

func NewProblemHTTPClient(client *http.Client) ProblemHTTPClient {
	return &ProblemHTTPClientImpl{client}
}

func (c *ProblemHTTPClientImpl) Backfill(ctx context.Context, in *BackfillReq, opts ...http.CallOption) (*BackfillRes, error) {
	var out BackfillRes
	pattern := "/v1/core/problem/backfill"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationProblemBackfill))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// EmergencyStop 紧急停止：暂停 AI 并清空分析队列（兼容）
func (c *ProblemHTTPClientImpl) EmergencyStop(ctx context.Context, in *EmergencyStopReq, opts ...http.CallOption) (*EmergencyStopRes, error) {
	var out EmergencyStopRes
	pattern := "/v1/core/problem/emergency-stop"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationProblemEmergencyStop))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ProblemHTTPClientImpl) Get(ctx context.Context, in *GetProblemReq, opts ...http.CallOption) (*GetProblemRes, error) {
	var out GetProblemRes
	pattern := "/v1/core/problem/get"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationProblemGet))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ProblemHTTPClientImpl) List(ctx context.Context, in *ListProblemReq, opts ...http.CallOption) (*ListProblemRes, error) {
	var out ListProblemRes
	pattern := "/v1/core/problem/list"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationProblemList))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ProblemHTTPClientImpl) ListSubmissions(ctx context.Context, in *ListSubmissionsReq, opts ...http.CallOption) (*ListSubmissionsRes, error) {
	var out ListSubmissionsRes
	pattern := "/v1/core/problem/submissions"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationProblemListSubmissions))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ProblemHTTPClientImpl) Progress(ctx context.Context, in *ProgressReq, opts ...http.CallOption) (*ProgressRes, error) {
	var out ProgressRes
	pattern := "/v1/core/problem/progress"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationProblemProgress))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ResetAll 全部重置：清空 AI 标签，保留题面，可选重新入队分析
func (c *ProblemHTTPClientImpl) ResetAll(ctx context.Context, in *ResetAllReq, opts ...http.CallOption) (*ResetAllRes, error) {
	var out ResetAllRes
	pattern := "/v1/core/problem/reset-all"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationProblemResetAll))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Resume 恢复 AI（兼容）
func (c *ProblemHTTPClientImpl) Resume(ctx context.Context, in *ResumeReq, opts ...http.CallOption) (*ResumeRes, error) {
	var out ResumeRes
	pattern := "/v1/core/problem/resume"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationProblemResume))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// RetryFailed 重试错误队列：仅重入 FAILED（可重试），排除 FAILED_PERM 黑名单
func (c *ProblemHTTPClientImpl) RetryFailed(ctx context.Context, in *RetryFailedReq, opts ...http.CallOption) (*RetryFailedRes, error) {
	var out RetryFailedRes
	pattern := "/v1/core/problem/retry-failed"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationProblemRetryFailed))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ToggleAnalyze 暂停/恢复 AI 分析（暂停时清空分析队列）
func (c *ProblemHTTPClientImpl) ToggleAnalyze(ctx context.Context, in *TogglePipelineReq, opts ...http.CallOption) (*TogglePipelineRes, error) {
	var out TogglePipelineRes
	pattern := "/v1/core/problem/toggle-analyze"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationProblemToggleAnalyze))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ToggleFetch 暂停/恢复题面爬取（暂停时清空爬取队列）
func (c *ProblemHTTPClientImpl) ToggleFetch(ctx context.Context, in *TogglePipelineReq, opts ...http.CallOption) (*TogglePipelineRes, error) {
	var out TogglePipelineRes
	pattern := "/v1/core/problem/toggle-fetch"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationProblemToggleFetch))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ProblemHTTPClientImpl) UserProfile(ctx context.Context, in *UserProfileReq, opts ...http.CallOption) (*UserProfileRes, error) {
	var out UserProfileRes
	pattern := "/v1/core/problem/user-profile"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationProblemUserProfile))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
