// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.33.1
// source: core/v1/problem/problem.proto

package problem

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Problem_List_FullMethodName            = "/api.core.v1.problem.Problem/List"
	Problem_Get_FullMethodName             = "/api.core.v1.problem.Problem/Get"
	Problem_ListSubmissions_FullMethodName = "/api.core.v1.problem.Problem/ListSubmissions"
	Problem_UserProfile_FullMethodName     = "/api.core.v1.problem.Problem/UserProfile"
	Problem_Progress_FullMethodName        = "/api.core.v1.problem.Problem/Progress"
	Problem_Backfill_FullMethodName        = "/api.core.v1.problem.Problem/Backfill"
)

// ProblemClient is the client API for Problem service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProblemClient interface {
	List(ctx context.Context, in *ListProblemReq, opts ...grpc.CallOption) (*ListProblemRes, error)
	Get(ctx context.Context, in *GetProblemReq, opts ...grpc.CallOption) (*GetProblemRes, error)
	ListSubmissions(ctx context.Context, in *ListSubmissionsReq, opts ...grpc.CallOption) (*ListSubmissionsRes, error)
	UserProfile(ctx context.Context, in *UserProfileReq, opts ...grpc.CallOption) (*UserProfileRes, error)
	Progress(ctx context.Context, in *ProgressReq, opts ...grpc.CallOption) (*ProgressRes, error)
	Backfill(ctx context.Context, in *BackfillReq, opts ...grpc.CallOption) (*BackfillRes, error)
}

type problemClient struct {
	cc grpc.ClientConnInterface
}

func NewProblemClient(cc grpc.ClientConnInterface) ProblemClient {
	return &problemClient{cc}
}

func (c *problemClient) List(ctx context.Context, in *ListProblemReq, opts ...grpc.CallOption) (*ListProblemRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProblemRes)
	err := c.cc.Invoke(ctx, Problem_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *problemClient) Get(ctx context.Context, in *GetProblemReq, opts ...grpc.CallOption) (*GetProblemRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProblemRes)
	err := c.cc.Invoke(ctx, Problem_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *problemClient) ListSubmissions(ctx context.Context, in *ListSubmissionsReq, opts ...grpc.CallOption) (*ListSubmissionsRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSubmissionsRes)
	err := c.cc.Invoke(ctx, Problem_ListSubmissions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *problemClient) UserProfile(ctx context.Context, in *UserProfileReq, opts ...grpc.CallOption) (*UserProfileRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserProfileRes)
	err := c.cc.Invoke(ctx, Problem_UserProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *problemClient) Progress(ctx context.Context, in *ProgressReq, opts ...grpc.CallOption) (*ProgressRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProgressRes)
	err := c.cc.Invoke(ctx, Problem_Progress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *problemClient) Backfill(ctx context.Context, in *BackfillReq, opts ...grpc.CallOption) (*BackfillRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BackfillRes)
	err := c.cc.Invoke(ctx, Problem_Backfill_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProblemServer is the server API for Problem service.
// All implementations must embed UnimplementedProblemServer
// for forward compatibility.
type ProblemServer interface {
	List(context.Context, *ListProblemReq) (*ListProblemRes, error)
	Get(context.Context, *GetProblemReq) (*GetProblemRes, error)
	ListSubmissions(context.Context, *ListSubmissionsReq) (*ListSubmissionsRes, error)
	UserProfile(context.Context, *UserProfileReq) (*UserProfileRes, error)
	Progress(context.Context, *ProgressReq) (*ProgressRes, error)
	Backfill(context.Context, *BackfillReq) (*BackfillRes, error)
	mustEmbedUnimplementedProblemServer()
}

// UnimplementedProblemServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProblemServer struct{}

func (UnimplementedProblemServer) List(context.Context, *ListProblemReq) (*ListProblemRes, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedProblemServer) Get(context.Context, *GetProblemReq) (*GetProblemRes, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedProblemServer) ListSubmissions(context.Context, *ListSubmissionsReq) (*ListSubmissionsRes, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSubmissions not implemented")
}
func (UnimplementedProblemServer) UserProfile(context.Context, *UserProfileReq) (*UserProfileRes, error) {
	return nil, status.Error(codes.Unimplemented, "method UserProfile not implemented")
}
func (UnimplementedProblemServer) Progress(context.Context, *ProgressReq) (*ProgressRes, error) {
	return nil, status.Error(codes.Unimplemented, "method Progress not implemented")
}
func (UnimplementedProblemServer) Backfill(context.Context, *BackfillReq) (*BackfillRes, error) {
	return nil, status.Error(codes.Unimplemented, "method Backfill not implemented")
}
func (UnimplementedProblemServer) mustEmbedUnimplementedProblemServer() {}
func (UnimplementedProblemServer) testEmbeddedByValue()                 {}

// UnsafeProblemServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProblemServer will
// result in compilation errors.
type UnsafeProblemServer interface {
	mustEmbedUnimplementedProblemServer()
}

func RegisterProblemServer(s grpc.ServiceRegistrar, srv ProblemServer) {
	// If the following call panics, it indicates UnimplementedProblemServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Problem_ServiceDesc, srv)
}

func _Problem_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProblemReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProblemServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Problem_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProblemServer).List(ctx, req.(*ListProblemReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Problem_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProblemReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProblemServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Problem_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProblemServer).Get(ctx, req.(*GetProblemReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Problem_ListSubmissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSubmissionsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProblemServer).ListSubmissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Problem_ListSubmissions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProblemServer).ListSubmissions(ctx, req.(*ListSubmissionsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Problem_UserProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserProfileReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProblemServer).UserProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Problem_UserProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProblemServer).UserProfile(ctx, req.(*UserProfileReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Problem_Progress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProgressReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProblemServer).Progress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Problem_Progress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProblemServer).Progress(ctx, req.(*ProgressReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Problem_Backfill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BackfillReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProblemServer).Backfill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Problem_Backfill_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProblemServer).Backfill(ctx, req.(*BackfillReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Problem_ServiceDesc is the grpc.ServiceDesc for Problem service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Problem_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.core.v1.problem.Problem",
	HandlerType: (*ProblemServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _Problem_List_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Problem_Get_Handler,
		},
		{
			MethodName: "ListSubmissions",
			Handler:    _Problem_ListSubmissions_Handler,
		},
		{
			MethodName: "UserProfile",
			Handler:    _Problem_UserProfile_Handler,
		},
		{
			MethodName: "Progress",
			Handler:    _Problem_Progress_Handler,
		},
		{
			MethodName: "Backfill",
			Handler:    _Problem_Backfill_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "core/v1/problem/problem.proto",
}
