// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: api/user/v1/profile/profile.proto

package profile

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetByIdReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByIdReq) Reset() {
	*x = GetByIdReq{}
	mi := &file_api_user_v1_profile_profile_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByIdReq) ProtoMessage() {}

func (x *GetByIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v1_profile_profile_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByIdReq.ProtoReflect.Descriptor instead.
func (*GetByIdReq) Descriptor() ([]byte, []int) {
	return file_api_user_v1_profile_profile_proto_rawDescGZIP(), []int{0}
}

func (x *GetByIdReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetByIdRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	GroupId       int64                  `protobuf:"varint,5,opt,name=groupId,proto3" json:"groupId,omitempty"`
	Avatar        string                 `protobuf:"bytes,6,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Spiders       []*GetByIdRes_Spiders  `protobuf:"bytes,7,rep,name=spiders,proto3" json:"spiders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByIdRes) Reset() {
	*x = GetByIdRes{}
	mi := &file_api_user_v1_profile_profile_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByIdRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByIdRes) ProtoMessage() {}

func (x *GetByIdRes) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v1_profile_profile_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByIdRes.ProtoReflect.Descriptor instead.
func (*GetByIdRes) Descriptor() ([]byte, []int) {
	return file_api_user_v1_profile_profile_proto_rawDescGZIP(), []int{1}
}

func (x *GetByIdRes) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetByIdRes) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GetByIdRes) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetByIdRes) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *GetByIdRes) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *GetByIdRes) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *GetByIdRes) GetSpiders() []*GetByIdRes_Spiders {
	if x != nil {
		return x.Spiders
	}
	return nil
}

type GetListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int64                  `protobuf:"varint,1,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	PageNum       int64                  `protobuf:"varint,2,opt,name=pageNum,proto3" json:"pageNum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetListReq) Reset() {
	*x = GetListReq{}
	mi := &file_api_user_v1_profile_profile_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListReq) ProtoMessage() {}

func (x *GetListReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v1_profile_profile_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListReq.ProtoReflect.Descriptor instead.
func (*GetListReq) Descriptor() ([]byte, []int) {
	return file_api_user_v1_profile_profile_proto_rawDescGZIP(), []int{2}
}

func (x *GetListReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetListReq) GetPageNum() int64 {
	if x != nil {
		return x.PageNum
	}
	return 0
}

type GetListRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*GetListRes_List     `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetListRes) Reset() {
	*x = GetListRes{}
	mi := &file_api_user_v1_profile_profile_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListRes) ProtoMessage() {}

func (x *GetListRes) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v1_profile_profile_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListRes.ProtoReflect.Descriptor instead.
func (*GetListRes) Descriptor() ([]byte, []int) {
	return file_api_user_v1_profile_profile_proto_rawDescGZIP(), []int{3}
}

func (x *GetListRes) GetList() []*GetListRes_List {
	if x != nil {
		return x.List
	}
	return nil
}

type UpdateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Avatar        string                 `protobuf:"bytes,6,opt,name=avatar,proto3" json:"avatar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateReq) Reset() {
	*x = UpdateReq{}
	mi := &file_api_user_v1_profile_profile_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateReq) ProtoMessage() {}

func (x *UpdateReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v1_profile_profile_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateReq.ProtoReflect.Descriptor instead.
func (*UpdateReq) Descriptor() ([]byte, []int) {
	return file_api_user_v1_profile_profile_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdateReq) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

type UpdateRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRes) Reset() {
	*x = UpdateRes{}
	mi := &file_api_user_v1_profile_profile_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRes) ProtoMessage() {}

func (x *UpdateRes) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v1_profile_profile_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRes.ProtoReflect.Descriptor instead.
func (*UpdateRes) Descriptor() ([]byte, []int) {
	return file_api_user_v1_profile_profile_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateRes) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UpdateRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetByIdRes_Spiders struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Platform      string                 `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByIdRes_Spiders) Reset() {
	*x = GetByIdRes_Spiders{}
	mi := &file_api_user_v1_profile_profile_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByIdRes_Spiders) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByIdRes_Spiders) ProtoMessage() {}

func (x *GetByIdRes_Spiders) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v1_profile_profile_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByIdRes_Spiders.ProtoReflect.Descriptor instead.
func (*GetByIdRes_Spiders) Descriptor() ([]byte, []int) {
	return file_api_user_v1_profile_profile_proto_rawDescGZIP(), []int{1, 0}
}

func (x *GetByIdRes_Spiders) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *GetByIdRes_Spiders) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type GetListRes_List struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	GroupId       int64                  `protobuf:"varint,5,opt,name=groupId,proto3" json:"groupId,omitempty"`
	Avatar        string                 `protobuf:"bytes,6,opt,name=avatar,proto3" json:"avatar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetListRes_List) Reset() {
	*x = GetListRes_List{}
	mi := &file_api_user_v1_profile_profile_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListRes_List) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListRes_List) ProtoMessage() {}

func (x *GetListRes_List) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v1_profile_profile_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListRes_List.ProtoReflect.Descriptor instead.
func (*GetListRes_List) Descriptor() ([]byte, []int) {
	return file_api_user_v1_profile_profile_proto_rawDescGZIP(), []int{3, 0}
}

func (x *GetListRes_List) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetListRes_List) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GetListRes_List) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetListRes_List) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *GetListRes_List) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

var File_api_user_v1_profile_profile_proto protoreflect.FileDescriptor

const file_api_user_v1_profile_profile_proto_rawDesc = "" +
	"\n" +
	"!api/user/v1/profile/profile.proto\x12\vapi.user.v1\x1a\x1cgoogle/api/annotations.proto\"$\n" +
	"\n" +
	"GetByIdReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\"\x9a\x02\n" +
	"\n" +
	"GetByIdRes\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x04R\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x18\n" +
	"\agroupId\x18\x05 \x01(\x03R\agroupId\x12\x16\n" +
	"\x06avatar\x18\x06 \x01(\tR\x06avatar\x129\n" +
	"\aspiders\x18\a \x03(\v2\x1f.api.user.v1.GetByIdRes.SpidersR\aspiders\x1aA\n" +
	"\aSpiders\x12\x1a\n" +
	"\bplatform\x18\x01 \x01(\tR\bplatform\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\"B\n" +
	"\n" +
	"GetListReq\x12\x1a\n" +
	"\bpageSize\x18\x01 \x01(\x03R\bpageSize\x12\x18\n" +
	"\apageNum\x18\x02 \x01(\x03R\apageNum\"\xc1\x01\n" +
	"\n" +
	"GetListRes\x120\n" +
	"\x04list\x18\x01 \x03(\v2\x1c.api.user.v1.GetListRes.ListR\x04list\x1a\x80\x01\n" +
	"\x04List\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x04R\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x18\n" +
	"\agroupId\x18\x05 \x01(\x03R\agroupId\x12\x16\n" +
	"\x06avatar\x18\x06 \x01(\tR\x06avatar\"e\n" +
	"\tUpdateReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x04R\x06userId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x16\n" +
	"\x06avatar\x18\x06 \x01(\tR\x06avatar\"9\n" +
	"\tUpdateRes\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xa4\x02\n" +
	"\aProfile\x12_\n" +
	"\aGetById\x12\x17.api.user.v1.GetByIdReq\x1a\x17.api.user.v1.GetByIdRes\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/v1/user/profile/get-by-id\x12Z\n" +
	"\aGetList\x12\x17.api.user.v1.GetListReq\x1a\x17.api.user.v1.GetListRes\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/v1/user/profile/list\x12\\\n" +
	"\x06Update\x12\x16.api.user.v1.UpdateReq\x1a\x16.api.user.v1.UpdateRes\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/v1/user/profile/updateB6\n" +
	"\vapi.user.v1P\x01Z%cwxu-algo/api/user/v1/profile;profileb\x06proto3"

var (
	file_api_user_v1_profile_profile_proto_rawDescOnce sync.Once
	file_api_user_v1_profile_profile_proto_rawDescData []byte
)

func file_api_user_v1_profile_profile_proto_rawDescGZIP() []byte {
	file_api_user_v1_profile_profile_proto_rawDescOnce.Do(func() {
		file_api_user_v1_profile_profile_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_user_v1_profile_profile_proto_rawDesc), len(file_api_user_v1_profile_profile_proto_rawDesc)))
	})
	return file_api_user_v1_profile_profile_proto_rawDescData
}

var file_api_user_v1_profile_profile_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_user_v1_profile_profile_proto_goTypes = []any{
	(*GetByIdReq)(nil),         // 0: api.user.v1.GetByIdReq
	(*GetByIdRes)(nil),         // 1: api.user.v1.GetByIdRes
	(*GetListReq)(nil),         // 2: api.user.v1.GetListReq
	(*GetListRes)(nil),         // 3: api.user.v1.GetListRes
	(*UpdateReq)(nil),          // 4: api.user.v1.UpdateReq
	(*UpdateRes)(nil),          // 5: api.user.v1.UpdateRes
	(*GetByIdRes_Spiders)(nil), // 6: api.user.v1.GetByIdRes.Spiders
	(*GetListRes_List)(nil),    // 7: api.user.v1.GetListRes.List
}
var file_api_user_v1_profile_profile_proto_depIdxs = []int32{
	6, // 0: api.user.v1.GetByIdRes.spiders:type_name -> api.user.v1.GetByIdRes.Spiders
	7, // 1: api.user.v1.GetListRes.list:type_name -> api.user.v1.GetListRes.List
	0, // 2: api.user.v1.Profile.GetById:input_type -> api.user.v1.GetByIdReq
	2, // 3: api.user.v1.Profile.GetList:input_type -> api.user.v1.GetListReq
	4, // 4: api.user.v1.Profile.Update:input_type -> api.user.v1.UpdateReq
	1, // 5: api.user.v1.Profile.GetById:output_type -> api.user.v1.GetByIdRes
	3, // 6: api.user.v1.Profile.GetList:output_type -> api.user.v1.GetListRes
	5, // 7: api.user.v1.Profile.Update:output_type -> api.user.v1.UpdateRes
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_user_v1_profile_profile_proto_init() }
func file_api_user_v1_profile_profile_proto_init() {
	if File_api_user_v1_profile_profile_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_user_v1_profile_profile_proto_rawDesc), len(file_api_user_v1_profile_profile_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_user_v1_profile_profile_proto_goTypes,
		DependencyIndexes: file_api_user_v1_profile_profile_proto_depIdxs,
		MessageInfos:      file_api_user_v1_profile_profile_proto_msgTypes,
	}.Build()
	File_api_user_v1_profile_profile_proto = out.File
	file_api_user_v1_profile_profile_proto_goTypes = nil
	file_api_user_v1_profile_profile_proto_depIdxs = nil
}
