// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: api/user/v1/profile/profile.proto

package profile

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetByIdReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByIdReq) Reset() {
	*x = GetByIdReq{}
	mi := &file_api_user_v1_profile_profile_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByIdReq) ProtoMessage() {}

func (x *GetByIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v1_profile_profile_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByIdReq.ProtoReflect.Descriptor instead.
func (*GetByIdReq) Descriptor() ([]byte, []int) {
	return file_api_user_v1_profile_profile_proto_rawDescGZIP(), []int{0}
}

func (x *GetByIdReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetByIdRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	GroupId       int64                  `protobuf:"varint,5,opt,name=groupId,proto3" json:"groupId,omitempty"`
	Avatar        string                 `protobuf:"bytes,6,opt,name=avatar,proto3" json:"avatar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByIdRes) Reset() {
	*x = GetByIdRes{}
	mi := &file_api_user_v1_profile_profile_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByIdRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByIdRes) ProtoMessage() {}

func (x *GetByIdRes) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_v1_profile_profile_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByIdRes.ProtoReflect.Descriptor instead.
func (*GetByIdRes) Descriptor() ([]byte, []int) {
	return file_api_user_v1_profile_profile_proto_rawDescGZIP(), []int{1}
}

func (x *GetByIdRes) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetByIdRes) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GetByIdRes) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetByIdRes) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *GetByIdRes) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *GetByIdRes) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

var File_api_user_v1_profile_profile_proto protoreflect.FileDescriptor

const file_api_user_v1_profile_profile_proto_rawDesc = "" +
	"\n" +
	"!api/user/v1/profile/profile.proto\x12\vapi.user.v1\x1a\x1cgoogle/api/annotations.proto\"$\n" +
	"\n" +
	"GetByIdReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\"\x9c\x01\n" +
	"\n" +
	"GetByIdRes\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x04R\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x18\n" +
	"\agroupId\x18\x05 \x01(\x03R\agroupId\x12\x16\n" +
	"\x06avatar\x18\x06 \x01(\tR\x06avatar2j\n" +
	"\aProfile\x12_\n" +
	"\aGetById\x12\x17.api.user.v1.GetByIdReq\x1a\x17.api.user.v1.GetByIdRes\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/v1/user/profile/get-by-idB6\n" +
	"\vapi.user.v1P\x01Z%cwxu-algo/api/user/v1/profile;profileb\x06proto3"

var (
	file_api_user_v1_profile_profile_proto_rawDescOnce sync.Once
	file_api_user_v1_profile_profile_proto_rawDescData []byte
)

func file_api_user_v1_profile_profile_proto_rawDescGZIP() []byte {
	file_api_user_v1_profile_profile_proto_rawDescOnce.Do(func() {
		file_api_user_v1_profile_profile_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_user_v1_profile_profile_proto_rawDesc), len(file_api_user_v1_profile_profile_proto_rawDesc)))
	})
	return file_api_user_v1_profile_profile_proto_rawDescData
}

var file_api_user_v1_profile_profile_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_user_v1_profile_profile_proto_goTypes = []any{
	(*GetByIdReq)(nil), // 0: api.user.v1.GetByIdReq
	(*GetByIdRes)(nil), // 1: api.user.v1.GetByIdRes
}
var file_api_user_v1_profile_profile_proto_depIdxs = []int32{
	0, // 0: api.user.v1.Profile.GetById:input_type -> api.user.v1.GetByIdReq
	1, // 1: api.user.v1.Profile.GetById:output_type -> api.user.v1.GetByIdRes
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_user_v1_profile_profile_proto_init() }
func file_api_user_v1_profile_profile_proto_init() {
	if File_api_user_v1_profile_profile_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_user_v1_profile_profile_proto_rawDesc), len(file_api_user_v1_profile_profile_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_user_v1_profile_profile_proto_goTypes,
		DependencyIndexes: file_api_user_v1_profile_profile_proto_depIdxs,
		MessageInfos:      file_api_user_v1_profile_profile_proto_msgTypes,
	}.Build()
	File_api_user_v1_profile_profile_proto = out.File
	file_api_user_v1_profile_profile_proto_goTypes = nil
	file_api_user_v1_profile_profile_proto_depIdxs = nil
}
