// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"cwxu-algo/app/common/conf"
	"cwxu-algo/app/common/discovery"
	"cwxu-algo/app/common/event"
	service2 "cwxu-algo/app/core_data/internal/biz/service"
	"cwxu-algo/app/core_data/internal/data"
	"cwxu-algo/app/core_data/internal/data/dal"
	"cwxu-algo/app/core_data/internal/server"
	"cwxu-algo/app/core_data/internal/service"
	"cwxu-algo/app/core_data/task"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "cwxu-algo/app/core_data/internal/spider/platform"
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger, aiAnalyze *conf.AiAnalyze) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData)
	if err != nil {
		return nil, nil, err
	}
	rabbitMQ, cleanup2, err := event.NewRabbitMQ(confServer)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	client := data.NewDataRDB(dataData)
	db := data.NewDataDB(dataData)
	spiderTask := task.NewSpiderTask(rabbitMQ, client, db)
	spiderService := service.NewSpiderService(dataData, spiderTask)
	spiderDal := dal.NewSpiderDal(dataData)
	register := discovery.NewConsulRegister(confServer)
	submitLogService := service.NewSubmitLogService(spiderDal, dataData, register)
	statisticDal := dal.NewStatisticDal(db, client)
	statisticUseCase := service2.NewStatisticUseCase(statisticDal, client, register)
	statisticService := service.NewStatistic(statisticUseCase)
	grpcServer := server.NewGRPCServer(confServer, logger, spiderService, submitLogService, statisticService)
	contestLogService := service.NewContestLogService(spiderDal, dataData, register)
	bulletinDal := dal.NewBulletinDal(dataData)
	bulletinService := service.NewBulletinService(bulletinDal)
	problemTagger := service2.NewProblemTagger(aiAnalyze, client)
	problemUseCase := service2.NewProblemUseCase(dataData, rabbitMQ, problemTagger, register)
	problemService := service.NewProblemService(problemUseCase, register)
	emergencyDal := dal.NewEmergencyDal(dataData)
	emergencyService := service.NewEmergencyService(emergencyDal)
	contestCalendarDal := dal.NewContestCalendarDal(dataData)
	contestCalendarService := service.NewContestCalendarService(contestCalendarDal, register, dataData)
	httpServer := server.NewHTTPServer(confServer, logger, dataData, submitLogService, spiderService, statisticService, contestLogService, bulletinService, problemService, emergencyService, contestCalendarService)
	spiderUseCase := service2.NewSpiderUseCase(dataData, problemUseCase)
	consumer := service2.NewConsumer(rabbitMQ, spiderUseCase, spiderTask)
	problemFetchConsumer := service2.NewProblemFetchConsumer(rabbitMQ, problemUseCase)
	problemAnalyzeConsumer := service2.NewProblemAnalyzeConsumer(rabbitMQ, problemUseCase)
	summaryTask := task.NewSummaryTask(rabbitMQ, client)
	cronTask := task.NewCronTask(spiderTask, dataData, summaryTask, register)
	app := newApp(logger, grpcServer, httpServer, register, consumer, problemFetchConsumer, problemAnalyzeConsumer, cronTask)
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}
