// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"cwxu-algo/app/common/conf"
	"cwxu-algo/app/common/discovery"
	"cwxu-algo/app/common/event"
	service2 "cwxu-algo/app/core_data/internal/biz/service"
	"cwxu-algo/app/core_data/internal/data"
	"cwxu-algo/app/core_data/internal/data/dal"
	"cwxu-algo/app/core_data/internal/server"
	"cwxu-algo/app/core_data/internal/service"
	"cwxu-algo/app/core_data/task"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "cwxu-algo/app/core_data/internal/spider/platform"
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData)
	if err != nil {
		return nil, nil, err
	}
	rabbitMQ, cleanup2, err := event.NewRabbitMQ(confServer)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	spiderTask := task.NewSpiderTask(rabbitMQ)
	spiderService := service.NewSpiderService(dataData, spiderTask)
	grpcServer := server.NewGRPCServer(confServer, logger, spiderService)
	spiderDal := dal.NewSpiderDal(dataData)
	submitLogService := service.NewSubmitLogService(spiderDal)
	httpServer := server.NewHTTPServer(confServer, logger, submitLogService, spiderService)
	register := discovery.NewConsulRegister(confServer)
	spiderUseCase := service2.NewSpiderUseCase(dataData)
	consumer := service2.NewConsumer(rabbitMQ, spiderUseCase)
	cronTask := task.NewCronTask(spiderTask, dataData)
	app := newApp(logger, grpcServer, httpServer, register, consumer, cronTask)
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}
