// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"cwxu-algo/app/agent/internal/agent"
	"cwxu-algo/app/agent/internal/biz/service"
	"cwxu-algo/app/agent/internal/server"
	"cwxu-algo/app/common/conf"
	"cwxu-algo/app/common/discovery"
	"cwxu-algo/app/common/event"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, data *conf.Data, logger log.Logger, smtp *conf.SMTP, confAgent *conf.Agent) (*kratos.App, func(), error) {
	grpcServer := server.NewGRPCServer(confServer, logger)
	httpServer := server.NewHTTPServer(confServer, logger)
	register := discovery.NewConsulRegister(confServer)
	rabbitMQ, cleanup, err := event.NewRabbitMQ(confServer)
	if err != nil {
		return nil, nil, err
	}
	chat := agent.NewChat(confAgent)
	summaryUseCase := service.NewSummaryUseCase(chat, smtp, register)
	consumer := service.NewConsumer(rabbitMQ, summaryUseCase)
	app := newApp(logger, grpcServer, httpServer, register, consumer)
	return app, func() {
		cleanup()
	}, nil
}
