// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: user/v1/site/site.proto

package site

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetConfigReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigReq) Reset() {
	*x = GetConfigReq{}
	mi := &file_user_v1_site_site_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigReq) ProtoMessage() {}

func (x *GetConfigReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_site_site_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigReq.ProtoReflect.Descriptor instead.
func (*GetConfigReq) Descriptor() ([]byte, []int) {
	return file_user_v1_site_site_proto_rawDescGZIP(), []int{0}
}

type GetConfigRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	SiteTitle     string                 `protobuf:"bytes,3,opt,name=site_title,json=siteTitle,proto3" json:"site_title,omitempty"`
	SiteLogo      string                 `protobuf:"bytes,4,opt,name=site_logo,json=siteLogo,proto3" json:"site_logo,omitempty"`
	Favicon       string                 `protobuf:"bytes,5,opt,name=favicon,proto3" json:"favicon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigRes) Reset() {
	*x = GetConfigRes{}
	mi := &file_user_v1_site_site_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigRes) ProtoMessage() {}

func (x *GetConfigRes) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_site_site_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigRes.ProtoReflect.Descriptor instead.
func (*GetConfigRes) Descriptor() ([]byte, []int) {
	return file_user_v1_site_site_proto_rawDescGZIP(), []int{1}
}

func (x *GetConfigRes) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetConfigRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetConfigRes) GetSiteTitle() string {
	if x != nil {
		return x.SiteTitle
	}
	return ""
}

func (x *GetConfigRes) GetSiteLogo() string {
	if x != nil {
		return x.SiteLogo
	}
	return ""
}

func (x *GetConfigRes) GetFavicon() string {
	if x != nil {
		return x.Favicon
	}
	return ""
}

type UpdateConfigReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SiteTitle     string                 `protobuf:"bytes,1,opt,name=site_title,json=siteTitle,proto3" json:"site_title,omitempty"`
	SiteLogo      string                 `protobuf:"bytes,2,opt,name=site_logo,json=siteLogo,proto3" json:"site_logo,omitempty"`
	Favicon       string                 `protobuf:"bytes,3,opt,name=favicon,proto3" json:"favicon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateConfigReq) Reset() {
	*x = UpdateConfigReq{}
	mi := &file_user_v1_site_site_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateConfigReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConfigReq) ProtoMessage() {}

func (x *UpdateConfigReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_site_site_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConfigReq.ProtoReflect.Descriptor instead.
func (*UpdateConfigReq) Descriptor() ([]byte, []int) {
	return file_user_v1_site_site_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateConfigReq) GetSiteTitle() string {
	if x != nil {
		return x.SiteTitle
	}
	return ""
}

func (x *UpdateConfigReq) GetSiteLogo() string {
	if x != nil {
		return x.SiteLogo
	}
	return ""
}

func (x *UpdateConfigReq) GetFavicon() string {
	if x != nil {
		return x.Favicon
	}
	return ""
}

type UpdateConfigRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	SiteTitle     string                 `protobuf:"bytes,3,opt,name=site_title,json=siteTitle,proto3" json:"site_title,omitempty"`
	SiteLogo      string                 `protobuf:"bytes,4,opt,name=site_logo,json=siteLogo,proto3" json:"site_logo,omitempty"`
	Favicon       string                 `protobuf:"bytes,5,opt,name=favicon,proto3" json:"favicon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateConfigRes) Reset() {
	*x = UpdateConfigRes{}
	mi := &file_user_v1_site_site_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateConfigRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConfigRes) ProtoMessage() {}

func (x *UpdateConfigRes) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_site_site_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConfigRes.ProtoReflect.Descriptor instead.
func (*UpdateConfigRes) Descriptor() ([]byte, []int) {
	return file_user_v1_site_site_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateConfigRes) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UpdateConfigRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateConfigRes) GetSiteTitle() string {
	if x != nil {
		return x.SiteTitle
	}
	return ""
}

func (x *UpdateConfigRes) GetSiteLogo() string {
	if x != nil {
		return x.SiteLogo
	}
	return ""
}

func (x *UpdateConfigRes) GetFavicon() string {
	if x != nil {
		return x.Favicon
	}
	return ""
}

var File_user_v1_site_site_proto protoreflect.FileDescriptor

const file_user_v1_site_site_proto_rawDesc = "" +
	"\n" +
	"\x17user/v1/site/site.proto\x12\x10api.user.v1.site\x1a\x1cgoogle/api/annotations.proto\"\x0e\n" +
	"\fGetConfigReq\"\x92\x01\n" +
	"\fGetConfigRes\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"site_title\x18\x03 \x01(\tR\tsiteTitle\x12\x1b\n" +
	"\tsite_logo\x18\x04 \x01(\tR\bsiteLogo\x12\x18\n" +
	"\afavicon\x18\x05 \x01(\tR\afavicon\"g\n" +
	"\x0fUpdateConfigReq\x12\x1d\n" +
	"\n" +
	"site_title\x18\x01 \x01(\tR\tsiteTitle\x12\x1b\n" +
	"\tsite_logo\x18\x02 \x01(\tR\bsiteLogo\x12\x18\n" +
	"\afavicon\x18\x03 \x01(\tR\afavicon\"\x95\x01\n" +
	"\x0fUpdateConfigRes\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"site_title\x18\x03 \x01(\tR\tsiteTitle\x12\x1b\n" +
	"\tsite_logo\x18\x04 \x01(\tR\bsiteLogo\x12\x18\n" +
	"\afavicon\x18\x05 \x01(\tR\afavicon2\xe8\x01\n" +
	"\x04Site\x12i\n" +
	"\tGetConfig\x12\x1e.api.user.v1.site.GetConfigReq\x1a\x1e.api.user.v1.site.GetConfigRes\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/v1/user/site/config\x12u\n" +
	"\fUpdateConfig\x12!.api.user.v1.site.UpdateConfigReq\x1a!.api.user.v1.site.UpdateConfigRes\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/v1/user/site/configB5\n" +
	"\x10api.user.v1.siteP\x01Z\x1fcwxu-algo/api/user/v1/site;siteb\x06proto3"

var (
	file_user_v1_site_site_proto_rawDescOnce sync.Once
	file_user_v1_site_site_proto_rawDescData []byte
)

func file_user_v1_site_site_proto_rawDescGZIP() []byte {
	file_user_v1_site_site_proto_rawDescOnce.Do(func() {
		file_user_v1_site_site_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_v1_site_site_proto_rawDesc), len(file_user_v1_site_site_proto_rawDesc)))
	})
	return file_user_v1_site_site_proto_rawDescData
}

var file_user_v1_site_site_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_user_v1_site_site_proto_goTypes = []any{
	(*GetConfigReq)(nil),    // 0: api.user.v1.site.GetConfigReq
	(*GetConfigRes)(nil),    // 1: api.user.v1.site.GetConfigRes
	(*UpdateConfigReq)(nil), // 2: api.user.v1.site.UpdateConfigReq
	(*UpdateConfigRes)(nil), // 3: api.user.v1.site.UpdateConfigRes
}
var file_user_v1_site_site_proto_depIdxs = []int32{
	0, // 0: api.user.v1.site.Site.GetConfig:input_type -> api.user.v1.site.GetConfigReq
	2, // 1: api.user.v1.site.Site.UpdateConfig:input_type -> api.user.v1.site.UpdateConfigReq
	1, // 2: api.user.v1.site.Site.GetConfig:output_type -> api.user.v1.site.GetConfigRes
	3, // 3: api.user.v1.site.Site.UpdateConfig:output_type -> api.user.v1.site.UpdateConfigRes
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_user_v1_site_site_proto_init() }
func file_user_v1_site_site_proto_init() {
	if File_user_v1_site_site_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_v1_site_site_proto_rawDesc), len(file_user_v1_site_site_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_v1_site_site_proto_goTypes,
		DependencyIndexes: file_user_v1_site_site_proto_depIdxs,
		MessageInfos:      file_user_v1_site_site_proto_msgTypes,
	}.Build()
	File_user_v1_site_site_proto = out.File
	file_user_v1_site_site_proto_goTypes = nil
	file_user_v1_site_site_proto_depIdxs = nil
}
