// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v6.33.1
// source: user/v1/site/site.proto

package site

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationSiteGetConfig = "/api.user.v1.site.Site/GetConfig"
const OperationSiteUpdateConfig = "/api.user.v1.site.Site/UpdateConfig"

type SiteHTTPServer interface {
	// GetConfig 公开：站点品牌配置
	GetConfig(context.Context, *GetConfigReq) (*GetConfigRes, error)
	// UpdateConfig 管理员：更新站点标题 / logo / favicon
	UpdateConfig(context.Context, *UpdateConfigReq) (*UpdateConfigRes, error)
}

func RegisterSiteHTTPServer(s *http.Server, srv SiteHTTPServer) {
	r := s.Route("/")
	r.GET("/v1/user/site/config", _Site_GetConfig0_HTTP_Handler(srv))
	r.POST("/v1/user/site/config", _Site_UpdateConfig0_HTTP_Handler(srv))
}

func _Site_GetConfig0_HTTP_Handler(srv SiteHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetConfigReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSiteGetConfig)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetConfig(ctx, req.(*GetConfigReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetConfigRes)
		return ctx.Result(200, reply)
	}
}

func _Site_UpdateConfig0_HTTP_Handler(srv SiteHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateConfigReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSiteUpdateConfig)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateConfig(ctx, req.(*UpdateConfigReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateConfigRes)
		return ctx.Result(200, reply)
	}
}

type SiteHTTPClient interface {
	// GetConfig 公开：站点品牌配置
	GetConfig(ctx context.Context, req *GetConfigReq, opts ...http.CallOption) (rsp *GetConfigRes, err error)
	// UpdateConfig 管理员：更新站点标题 / logo / favicon
	UpdateConfig(ctx context.Context, req *UpdateConfigReq, opts ...http.CallOption) (rsp *UpdateConfigRes, err error)
}

type SiteHTTPClientImpl struct {
	cc *http.Client
}

func NewSiteHTTPClient(client *http.Client) SiteHTTPClient {
	return &SiteHTTPClientImpl{client}
}

// GetConfig 公开：站点品牌配置
func (c *SiteHTTPClientImpl) GetConfig(ctx context.Context, in *GetConfigReq, opts ...http.CallOption) (*GetConfigRes, error) {
	var out GetConfigRes
	pattern := "/v1/user/site/config"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationSiteGetConfig))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateConfig 管理员：更新站点标题 / logo / favicon
func (c *SiteHTTPClientImpl) UpdateConfig(ctx context.Context, in *UpdateConfigReq, opts ...http.CallOption) (*UpdateConfigRes, error) {
	var out UpdateConfigRes
	pattern := "/v1/user/site/config"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationSiteUpdateConfig))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
