// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"cwxu-algo/app/common/conf"
	"cwxu-algo/app/common/discovery"
	"cwxu-algo/app/user/internal/data"
	"cwxu-algo/app/user/internal/data/dal"
	"cwxu-algo/app/user/internal/server"
	"cwxu-algo/app/user/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData)
	if err != nil {
		return nil, nil, err
	}
	profileDal := dal.NewProfileDal(dataData)
	register := discovery.NewConsulRegister(confServer)
	profileService := service.NewProfileService(profileDal, register)
	grpcServer := server.NewGRPCServer(confServer, logger, profileService)
	authService := service.NewAuthService(dataData)
	httpServer := server.NewHTTPServer(confServer, authService, profileService, logger)
	app := newApp(logger, grpcServer, httpServer, register)
	return app, func() {
		cleanup()
	}, nil
}
